package com.lnsoft.bd.fk.mapper;

import com.lnsoft.bd.fk.po.TXczyTxzy;
import com.lnsoft.bd.fk.po.TXczyTxzyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TXczyTxzyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int countByExample(TXczyTxzyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int deleteByExample(TXczyTxzyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int deleteByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int insert(TXczyTxzy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int insertSelective(TXczyTxzy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    List<TXczyTxzy> selectByExample(TXczyTxzyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    TXczyTxzy selectByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") TXczyTxzy record, @Param("example") TXczyTxzyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByExample(@Param("record") TXczyTxzy record, @Param("example") TXczyTxzyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByPrimaryKeySelective(TXczyTxzy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByPrimaryKey(TXczyTxzy record);
}