package com.lnsoft.bd.fk.mapper;

import com.lnsoft.bd.fk.po.TXczyZylcDetails;
import com.lnsoft.bd.fk.po.TXczyZylcDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TXczyZylcDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int countByExample(TXczyZylcDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int deleteByExample(TXczyZylcDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int deleteByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int insert(TXczyZylcDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int insertSelective(TXczyZylcDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    List<TXczyZylcDetails> selectByExample(TXczyZylcDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    TXczyZylcDetails selectByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") TXczyZylcDetails record, @Param("example") TXczyZylcDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByExample(@Param("record") TXczyZylcDetails record, @Param("example") TXczyZylcDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByPrimaryKeySelective(TXczyZylcDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByPrimaryKey(TXczyZylcDetails record);

	int batchinsert(List<TXczyZylcDetails> tXczyZylcDetails);
}