package com.lnsoft.bd.fk.mapper;

import com.lnsoft.bd.fk.po.TXczyFxdwj;
import com.lnsoft.bd.fk.po.TXczyFxdwjExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TXczyFxdwjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    int countByExample(TXczyFxdwjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    int deleteByExample(TXczyFxdwjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    int deleteByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    int insert(TXczyFxdwj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    int insertSelective(TXczyFxdwj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    List<TXczyFxdwj> selectByExample(TXczyFxdwjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    TXczyFxdwj selectByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") TXczyFxdwj record, @Param("example") TXczyFxdwjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    int updateByExample(@Param("record") TXczyFxdwj record, @Param("example") TXczyFxdwjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    int updateByPrimaryKeySelective(TXczyFxdwj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    int updateByPrimaryKey(TXczyFxdwj record);
}