package com.lnsoft.bd.fk.mapper;

import com.lnsoft.bd.fk.po.TXczyZylcFxd;
import com.lnsoft.bd.fk.po.TXczyZylcFxdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TXczyZylcFxdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_FXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int countByExample(TXczyZylcFxdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_FXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int deleteByExample(TXczyZylcFxdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_FXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int deleteByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_FXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int insert(TXczyZylcFxd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_FXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int insertSelective(TXczyZylcFxd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_FXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    List<TXczyZylcFxd> selectByExample(TXczyZylcFxdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_FXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    TXczyZylcFxd selectByPrimaryKey(String objId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_FXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") TXczyZylcFxd record, @Param("example") TXczyZylcFxdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_FXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByExample(@Param("record") TXczyZylcFxd record, @Param("example") TXczyZylcFxdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_FXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByPrimaryKeySelective(TXczyZylcFxd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_FXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    int updateByPrimaryKey(TXczyZylcFxd record);

	int batchinsert(List<TXczyZylcFxd> tXczyZylcFxds);
}