package com.lnsoft.bd.fk.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TXczyTxzyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public TXczyTxzyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andObjIdIsNull() {
            addCriterion("OBJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andObjIdIsNotNull() {
            addCriterion("OBJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andObjIdEqualTo(String value) {
            addCriterion("OBJ_ID =", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotEqualTo(String value) {
            addCriterion("OBJ_ID <>", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdGreaterThan(String value) {
            addCriterion("OBJ_ID >", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdGreaterThanOrEqualTo(String value) {
            addCriterion("OBJ_ID >=", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLessThan(String value) {
            addCriterion("OBJ_ID <", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLessThanOrEqualTo(String value) {
            addCriterion("OBJ_ID <=", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLike(String value) {
            addCriterion("OBJ_ID like", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotLike(String value) {
            addCriterion("OBJ_ID not like", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdIn(List<String> values) {
            addCriterion("OBJ_ID in", values, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotIn(List<String> values) {
            addCriterion("OBJ_ID not in", values, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdBetween(String value1, String value2) {
            addCriterion("OBJ_ID between", value1, value2, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotBetween(String value1, String value2) {
            addCriterion("OBJ_ID not between", value1, value2, "objId");
            return (Criteria) this;
        }

        public Criteria andZydlIsNull() {
            addCriterion("ZYDL is null");
            return (Criteria) this;
        }

        public Criteria andZydlIsNotNull() {
            addCriterion("ZYDL is not null");
            return (Criteria) this;
        }

        public Criteria andZydlEqualTo(String value) {
            addCriterion("ZYDL =", value, "zydl");
            return (Criteria) this;
        }

        public Criteria andZydlNotEqualTo(String value) {
            addCriterion("ZYDL <>", value, "zydl");
            return (Criteria) this;
        }

        public Criteria andZydlGreaterThan(String value) {
            addCriterion("ZYDL >", value, "zydl");
            return (Criteria) this;
        }

        public Criteria andZydlGreaterThanOrEqualTo(String value) {
            addCriterion("ZYDL >=", value, "zydl");
            return (Criteria) this;
        }

        public Criteria andZydlLessThan(String value) {
            addCriterion("ZYDL <", value, "zydl");
            return (Criteria) this;
        }

        public Criteria andZydlLessThanOrEqualTo(String value) {
            addCriterion("ZYDL <=", value, "zydl");
            return (Criteria) this;
        }

        public Criteria andZydlLike(String value) {
            addCriterion("ZYDL like", value, "zydl");
            return (Criteria) this;
        }

        public Criteria andZydlNotLike(String value) {
            addCriterion("ZYDL not like", value, "zydl");
            return (Criteria) this;
        }

        public Criteria andZydlIn(List<String> values) {
            addCriterion("ZYDL in", values, "zydl");
            return (Criteria) this;
        }

        public Criteria andZydlNotIn(List<String> values) {
            addCriterion("ZYDL not in", values, "zydl");
            return (Criteria) this;
        }

        public Criteria andZydlBetween(String value1, String value2) {
            addCriterion("ZYDL between", value1, value2, "zydl");
            return (Criteria) this;
        }

        public Criteria andZydlNotBetween(String value1, String value2) {
            addCriterion("ZYDL not between", value1, value2, "zydl");
            return (Criteria) this;
        }

        public Criteria andGzddmsIsNull() {
            addCriterion("GZDDMS is null");
            return (Criteria) this;
        }

        public Criteria andGzddmsIsNotNull() {
            addCriterion("GZDDMS is not null");
            return (Criteria) this;
        }

        public Criteria andGzddmsEqualTo(String value) {
            addCriterion("GZDDMS =", value, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzddmsNotEqualTo(String value) {
            addCriterion("GZDDMS <>", value, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzddmsGreaterThan(String value) {
            addCriterion("GZDDMS >", value, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzddmsGreaterThanOrEqualTo(String value) {
            addCriterion("GZDDMS >=", value, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzddmsLessThan(String value) {
            addCriterion("GZDDMS <", value, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzddmsLessThanOrEqualTo(String value) {
            addCriterion("GZDDMS <=", value, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzddmsLike(String value) {
            addCriterion("GZDDMS like", value, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzddmsNotLike(String value) {
            addCriterion("GZDDMS not like", value, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzddmsIn(List<String> values) {
            addCriterion("GZDDMS in", values, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzddmsNotIn(List<String> values) {
            addCriterion("GZDDMS not in", values, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzddmsBetween(String value1, String value2) {
            addCriterion("GZDDMS between", value1, value2, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzddmsNotBetween(String value1, String value2) {
            addCriterion("GZDDMS not between", value1, value2, "gzddms");
            return (Criteria) this;
        }

        public Criteria andGzpqfrIsNull() {
            addCriterion("GZPQFR is null");
            return (Criteria) this;
        }

        public Criteria andGzpqfrIsNotNull() {
            addCriterion("GZPQFR is not null");
            return (Criteria) this;
        }

        public Criteria andGzpqfrEqualTo(String value) {
            addCriterion("GZPQFR =", value, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGzpqfrNotEqualTo(String value) {
            addCriterion("GZPQFR <>", value, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGzpqfrGreaterThan(String value) {
            addCriterion("GZPQFR >", value, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGzpqfrGreaterThanOrEqualTo(String value) {
            addCriterion("GZPQFR >=", value, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGzpqfrLessThan(String value) {
            addCriterion("GZPQFR <", value, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGzpqfrLessThanOrEqualTo(String value) {
            addCriterion("GZPQFR <=", value, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGzpqfrLike(String value) {
            addCriterion("GZPQFR like", value, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGzpqfrNotLike(String value) {
            addCriterion("GZPQFR not like", value, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGzpqfrIn(List<String> values) {
            addCriterion("GZPQFR in", values, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGzpqfrNotIn(List<String> values) {
            addCriterion("GZPQFR not in", values, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGzpqfrBetween(String value1, String value2) {
            addCriterion("GZPQFR between", value1, value2, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGzpqfrNotBetween(String value1, String value2) {
            addCriterion("GZPQFR not between", value1, value2, "gzpqfr");
            return (Criteria) this;
        }

        public Criteria andGznrIsNull() {
            addCriterion("GZNR is null");
            return (Criteria) this;
        }

        public Criteria andGznrIsNotNull() {
            addCriterion("GZNR is not null");
            return (Criteria) this;
        }

        public Criteria andGznrEqualTo(String value) {
            addCriterion("GZNR =", value, "gznr");
            return (Criteria) this;
        }

        public Criteria andGznrNotEqualTo(String value) {
            addCriterion("GZNR <>", value, "gznr");
            return (Criteria) this;
        }

        public Criteria andGznrGreaterThan(String value) {
            addCriterion("GZNR >", value, "gznr");
            return (Criteria) this;
        }

        public Criteria andGznrGreaterThanOrEqualTo(String value) {
            addCriterion("GZNR >=", value, "gznr");
            return (Criteria) this;
        }

        public Criteria andGznrLessThan(String value) {
            addCriterion("GZNR <", value, "gznr");
            return (Criteria) this;
        }

        public Criteria andGznrLessThanOrEqualTo(String value) {
            addCriterion("GZNR <=", value, "gznr");
            return (Criteria) this;
        }

        public Criteria andGznrLike(String value) {
            addCriterion("GZNR like", value, "gznr");
            return (Criteria) this;
        }

        public Criteria andGznrNotLike(String value) {
            addCriterion("GZNR not like", value, "gznr");
            return (Criteria) this;
        }

        public Criteria andGznrIn(List<String> values) {
            addCriterion("GZNR in", values, "gznr");
            return (Criteria) this;
        }

        public Criteria andGznrNotIn(List<String> values) {
            addCriterion("GZNR not in", values, "gznr");
            return (Criteria) this;
        }

        public Criteria andGznrBetween(String value1, String value2) {
            addCriterion("GZNR between", value1, value2, "gznr");
            return (Criteria) this;
        }

        public Criteria andGznrNotBetween(String value1, String value2) {
            addCriterion("GZNR not between", value1, value2, "gznr");
            return (Criteria) this;
        }

        public Criteria andZyryIsNull() {
            addCriterion("ZYRY is null");
            return (Criteria) this;
        }

        public Criteria andZyryIsNotNull() {
            addCriterion("ZYRY is not null");
            return (Criteria) this;
        }

        public Criteria andZyryEqualTo(String value) {
            addCriterion("ZYRY =", value, "zyry");
            return (Criteria) this;
        }

        public Criteria andZyryNotEqualTo(String value) {
            addCriterion("ZYRY <>", value, "zyry");
            return (Criteria) this;
        }

        public Criteria andZyryGreaterThan(String value) {
            addCriterion("ZYRY >", value, "zyry");
            return (Criteria) this;
        }

        public Criteria andZyryGreaterThanOrEqualTo(String value) {
            addCriterion("ZYRY >=", value, "zyry");
            return (Criteria) this;
        }

        public Criteria andZyryLessThan(String value) {
            addCriterion("ZYRY <", value, "zyry");
            return (Criteria) this;
        }

        public Criteria andZyryLessThanOrEqualTo(String value) {
            addCriterion("ZYRY <=", value, "zyry");
            return (Criteria) this;
        }

        public Criteria andZyryLike(String value) {
            addCriterion("ZYRY like", value, "zyry");
            return (Criteria) this;
        }

        public Criteria andZyryNotLike(String value) {
            addCriterion("ZYRY not like", value, "zyry");
            return (Criteria) this;
        }

        public Criteria andZyryIn(List<String> values) {
            addCriterion("ZYRY in", values, "zyry");
            return (Criteria) this;
        }

        public Criteria andZyryNotIn(List<String> values) {
            addCriterion("ZYRY not in", values, "zyry");
            return (Criteria) this;
        }

        public Criteria andZyryBetween(String value1, String value2) {
            addCriterion("ZYRY between", value1, value2, "zyry");
            return (Criteria) this;
        }

        public Criteria andZyryNotBetween(String value1, String value2) {
            addCriterion("ZYRY not between", value1, value2, "zyry");
            return (Criteria) this;
        }

        public Criteria andZynrIsNull() {
            addCriterion("ZYNR is null");
            return (Criteria) this;
        }

        public Criteria andZynrIsNotNull() {
            addCriterion("ZYNR is not null");
            return (Criteria) this;
        }

        public Criteria andZynrEqualTo(String value) {
            addCriterion("ZYNR =", value, "zynr");
            return (Criteria) this;
        }

        public Criteria andZynrNotEqualTo(String value) {
            addCriterion("ZYNR <>", value, "zynr");
            return (Criteria) this;
        }

        public Criteria andZynrGreaterThan(String value) {
            addCriterion("ZYNR >", value, "zynr");
            return (Criteria) this;
        }

        public Criteria andZynrGreaterThanOrEqualTo(String value) {
            addCriterion("ZYNR >=", value, "zynr");
            return (Criteria) this;
        }

        public Criteria andZynrLessThan(String value) {
            addCriterion("ZYNR <", value, "zynr");
            return (Criteria) this;
        }

        public Criteria andZynrLessThanOrEqualTo(String value) {
            addCriterion("ZYNR <=", value, "zynr");
            return (Criteria) this;
        }

        public Criteria andZynrLike(String value) {
            addCriterion("ZYNR like", value, "zynr");
            return (Criteria) this;
        }

        public Criteria andZynrNotLike(String value) {
            addCriterion("ZYNR not like", value, "zynr");
            return (Criteria) this;
        }

        public Criteria andZynrIn(List<String> values) {
            addCriterion("ZYNR in", values, "zynr");
            return (Criteria) this;
        }

        public Criteria andZynrNotIn(List<String> values) {
            addCriterion("ZYNR not in", values, "zynr");
            return (Criteria) this;
        }

        public Criteria andZynrBetween(String value1, String value2) {
            addCriterion("ZYNR between", value1, value2, "zynr");
            return (Criteria) this;
        }

        public Criteria andZynrNotBetween(String value1, String value2) {
            addCriterion("ZYNR not between", value1, value2, "zynr");
            return (Criteria) this;
        }

        public Criteria andSsdsmcIsNull() {
            addCriterion("SSDSMC is null");
            return (Criteria) this;
        }

        public Criteria andSsdsmcIsNotNull() {
            addCriterion("SSDSMC is not null");
            return (Criteria) this;
        }

        public Criteria andSsdsmcEqualTo(String value) {
            addCriterion("SSDSMC =", value, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andSsdsmcNotEqualTo(String value) {
            addCriterion("SSDSMC <>", value, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andSsdsmcGreaterThan(String value) {
            addCriterion("SSDSMC >", value, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andSsdsmcGreaterThanOrEqualTo(String value) {
            addCriterion("SSDSMC >=", value, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andSsdsmcLessThan(String value) {
            addCriterion("SSDSMC <", value, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andSsdsmcLessThanOrEqualTo(String value) {
            addCriterion("SSDSMC <=", value, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andSsdsmcLike(String value) {
            addCriterion("SSDSMC like", value, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andSsdsmcNotLike(String value) {
            addCriterion("SSDSMC not like", value, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andSsdsmcIn(List<String> values) {
            addCriterion("SSDSMC in", values, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andSsdsmcNotIn(List<String> values) {
            addCriterion("SSDSMC not in", values, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andSsdsmcBetween(String value1, String value2) {
            addCriterion("SSDSMC between", value1, value2, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andSsdsmcNotBetween(String value1, String value2) {
            addCriterion("SSDSMC not between", value1, value2, "ssdsmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcIsNull() {
            addCriterion("GZBZMC is null");
            return (Criteria) this;
        }

        public Criteria andGzbzmcIsNotNull() {
            addCriterion("GZBZMC is not null");
            return (Criteria) this;
        }

        public Criteria andGzbzmcEqualTo(String value) {
            addCriterion("GZBZMC =", value, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcNotEqualTo(String value) {
            addCriterion("GZBZMC <>", value, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcGreaterThan(String value) {
            addCriterion("GZBZMC >", value, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcGreaterThanOrEqualTo(String value) {
            addCriterion("GZBZMC >=", value, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcLessThan(String value) {
            addCriterion("GZBZMC <", value, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcLessThanOrEqualTo(String value) {
            addCriterion("GZBZMC <=", value, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcLike(String value) {
            addCriterion("GZBZMC like", value, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcNotLike(String value) {
            addCriterion("GZBZMC not like", value, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcIn(List<String> values) {
            addCriterion("GZBZMC in", values, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcNotIn(List<String> values) {
            addCriterion("GZBZMC not in", values, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcBetween(String value1, String value2) {
            addCriterion("GZBZMC between", value1, value2, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andGzbzmcNotBetween(String value1, String value2) {
            addCriterion("GZBZMC not between", value1, value2, "gzbzmc");
            return (Criteria) this;
        }

        public Criteria andSsdsidIsNull() {
            addCriterion("SSDSID is null");
            return (Criteria) this;
        }

        public Criteria andSsdsidIsNotNull() {
            addCriterion("SSDSID is not null");
            return (Criteria) this;
        }

        public Criteria andSsdsidEqualTo(String value) {
            addCriterion("SSDSID =", value, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andSsdsidNotEqualTo(String value) {
            addCriterion("SSDSID <>", value, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andSsdsidGreaterThan(String value) {
            addCriterion("SSDSID >", value, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andSsdsidGreaterThanOrEqualTo(String value) {
            addCriterion("SSDSID >=", value, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andSsdsidLessThan(String value) {
            addCriterion("SSDSID <", value, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andSsdsidLessThanOrEqualTo(String value) {
            addCriterion("SSDSID <=", value, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andSsdsidLike(String value) {
            addCriterion("SSDSID like", value, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andSsdsidNotLike(String value) {
            addCriterion("SSDSID not like", value, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andSsdsidIn(List<String> values) {
            addCriterion("SSDSID in", values, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andSsdsidNotIn(List<String> values) {
            addCriterion("SSDSID not in", values, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andSsdsidBetween(String value1, String value2) {
            addCriterion("SSDSID between", value1, value2, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andSsdsidNotBetween(String value1, String value2) {
            addCriterion("SSDSID not between", value1, value2, "ssdsid");
            return (Criteria) this;
        }

        public Criteria andGzbzidIsNull() {
            addCriterion("GZBZID is null");
            return (Criteria) this;
        }

        public Criteria andGzbzidIsNotNull() {
            addCriterion("GZBZID is not null");
            return (Criteria) this;
        }

        public Criteria andGzbzidEqualTo(String value) {
            addCriterion("GZBZID =", value, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andGzbzidNotEqualTo(String value) {
            addCriterion("GZBZID <>", value, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andGzbzidGreaterThan(String value) {
            addCriterion("GZBZID >", value, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andGzbzidGreaterThanOrEqualTo(String value) {
            addCriterion("GZBZID >=", value, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andGzbzidLessThan(String value) {
            addCriterion("GZBZID <", value, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andGzbzidLessThanOrEqualTo(String value) {
            addCriterion("GZBZID <=", value, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andGzbzidLike(String value) {
            addCriterion("GZBZID like", value, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andGzbzidNotLike(String value) {
            addCriterion("GZBZID not like", value, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andGzbzidIn(List<String> values) {
            addCriterion("GZBZID in", values, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andGzbzidNotIn(List<String> values) {
            addCriterion("GZBZID not in", values, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andGzbzidBetween(String value1, String value2) {
            addCriterion("GZBZID between", value1, value2, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andGzbzidNotBetween(String value1, String value2) {
            addCriterion("GZBZID not between", value1, value2, "gzbzid");
            return (Criteria) this;
        }

        public Criteria andKgsjIsNull() {
            addCriterion("KGSJ is null");
            return (Criteria) this;
        }

        public Criteria andKgsjIsNotNull() {
            addCriterion("KGSJ is not null");
            return (Criteria) this;
        }

        public Criteria andKgsjEqualTo(Date value) {
            addCriterionForJDBCDate("KGSJ =", value, "kgsj");
            return (Criteria) this;
        }

        public Criteria andKgsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("KGSJ <>", value, "kgsj");
            return (Criteria) this;
        }

        public Criteria andKgsjGreaterThan(Date value) {
            addCriterionForJDBCDate("KGSJ >", value, "kgsj");
            return (Criteria) this;
        }

        public Criteria andKgsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("KGSJ >=", value, "kgsj");
            return (Criteria) this;
        }

        public Criteria andKgsjLessThan(Date value) {
            addCriterionForJDBCDate("KGSJ <", value, "kgsj");
            return (Criteria) this;
        }

        public Criteria andKgsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("KGSJ <=", value, "kgsj");
            return (Criteria) this;
        }

        public Criteria andKgsjIn(List<Date> values) {
            addCriterionForJDBCDate("KGSJ in", values, "kgsj");
            return (Criteria) this;
        }

        public Criteria andKgsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("KGSJ not in", values, "kgsj");
            return (Criteria) this;
        }

        public Criteria andKgsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("KGSJ between", value1, value2, "kgsj");
            return (Criteria) this;
        }

        public Criteria andKgsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("KGSJ not between", value1, value2, "kgsj");
            return (Criteria) this;
        }

        public Criteria andZylxIsNull() {
            addCriterion("ZYLX is null");
            return (Criteria) this;
        }

        public Criteria andZylxIsNotNull() {
            addCriterion("ZYLX is not null");
            return (Criteria) this;
        }

        public Criteria andZylxEqualTo(String value) {
            addCriterion("ZYLX =", value, "zylx");
            return (Criteria) this;
        }

        public Criteria andZylxNotEqualTo(String value) {
            addCriterion("ZYLX <>", value, "zylx");
            return (Criteria) this;
        }

        public Criteria andZylxGreaterThan(String value) {
            addCriterion("ZYLX >", value, "zylx");
            return (Criteria) this;
        }

        public Criteria andZylxGreaterThanOrEqualTo(String value) {
            addCriterion("ZYLX >=", value, "zylx");
            return (Criteria) this;
        }

        public Criteria andZylxLessThan(String value) {
            addCriterion("ZYLX <", value, "zylx");
            return (Criteria) this;
        }

        public Criteria andZylxLessThanOrEqualTo(String value) {
            addCriterion("ZYLX <=", value, "zylx");
            return (Criteria) this;
        }

        public Criteria andZylxLike(String value) {
            addCriterion("ZYLX like", value, "zylx");
            return (Criteria) this;
        }

        public Criteria andZylxNotLike(String value) {
            addCriterion("ZYLX not like", value, "zylx");
            return (Criteria) this;
        }

        public Criteria andZylxIn(List<String> values) {
            addCriterion("ZYLX in", values, "zylx");
            return (Criteria) this;
        }

        public Criteria andZylxNotIn(List<String> values) {
            addCriterion("ZYLX not in", values, "zylx");
            return (Criteria) this;
        }

        public Criteria andZylxBetween(String value1, String value2) {
            addCriterion("ZYLX between", value1, value2, "zylx");
            return (Criteria) this;
        }

        public Criteria andZylxNotBetween(String value1, String value2) {
            addCriterion("ZYLX not between", value1, value2, "zylx");
            return (Criteria) this;
        }

        public Criteria andScyaIsNull() {
            addCriterion("SCYA is null");
            return (Criteria) this;
        }

        public Criteria andScyaIsNotNull() {
            addCriterion("SCYA is not null");
            return (Criteria) this;
        }

        public Criteria andScyaEqualTo(String value) {
            addCriterion("SCYA =", value, "scya");
            return (Criteria) this;
        }

        public Criteria andScyaNotEqualTo(String value) {
            addCriterion("SCYA <>", value, "scya");
            return (Criteria) this;
        }

        public Criteria andScyaGreaterThan(String value) {
            addCriterion("SCYA >", value, "scya");
            return (Criteria) this;
        }

        public Criteria andScyaGreaterThanOrEqualTo(String value) {
            addCriterion("SCYA >=", value, "scya");
            return (Criteria) this;
        }

        public Criteria andScyaLessThan(String value) {
            addCriterion("SCYA <", value, "scya");
            return (Criteria) this;
        }

        public Criteria andScyaLessThanOrEqualTo(String value) {
            addCriterion("SCYA <=", value, "scya");
            return (Criteria) this;
        }

        public Criteria andScyaLike(String value) {
            addCriterion("SCYA like", value, "scya");
            return (Criteria) this;
        }

        public Criteria andScyaNotLike(String value) {
            addCriterion("SCYA not like", value, "scya");
            return (Criteria) this;
        }

        public Criteria andScyaIn(List<String> values) {
            addCriterion("SCYA in", values, "scya");
            return (Criteria) this;
        }

        public Criteria andScyaNotIn(List<String> values) {
            addCriterion("SCYA not in", values, "scya");
            return (Criteria) this;
        }

        public Criteria andScyaBetween(String value1, String value2) {
            addCriterion("SCYA between", value1, value2, "scya");
            return (Criteria) this;
        }

        public Criteria andScyaNotBetween(String value1, String value2) {
            addCriterion("SCYA not between", value1, value2, "scya");
            return (Criteria) this;
        }

        public Criteria andGzrysIsNull() {
            addCriterion("GZRYS is null");
            return (Criteria) this;
        }

        public Criteria andGzrysIsNotNull() {
            addCriterion("GZRYS is not null");
            return (Criteria) this;
        }

        public Criteria andGzrysEqualTo(String value) {
            addCriterion("GZRYS =", value, "gzrys");
            return (Criteria) this;
        }

        public Criteria andGzrysNotEqualTo(String value) {
            addCriterion("GZRYS <>", value, "gzrys");
            return (Criteria) this;
        }

        public Criteria andGzrysGreaterThan(String value) {
            addCriterion("GZRYS >", value, "gzrys");
            return (Criteria) this;
        }

        public Criteria andGzrysGreaterThanOrEqualTo(String value) {
            addCriterion("GZRYS >=", value, "gzrys");
            return (Criteria) this;
        }

        public Criteria andGzrysLessThan(String value) {
            addCriterion("GZRYS <", value, "gzrys");
            return (Criteria) this;
        }

        public Criteria andGzrysLessThanOrEqualTo(String value) {
            addCriterion("GZRYS <=", value, "gzrys");
            return (Criteria) this;
        }

        public Criteria andGzrysLike(String value) {
            addCriterion("GZRYS like", value, "gzrys");
            return (Criteria) this;
        }

        public Criteria andGzrysNotLike(String value) {
            addCriterion("GZRYS not like", value, "gzrys");
            return (Criteria) this;
        }

        public Criteria andGzrysIn(List<String> values) {
            addCriterion("GZRYS in", values, "gzrys");
            return (Criteria) this;
        }

        public Criteria andGzrysNotIn(List<String> values) {
            addCriterion("GZRYS not in", values, "gzrys");
            return (Criteria) this;
        }

        public Criteria andGzrysBetween(String value1, String value2) {
            addCriterion("GZRYS between", value1, value2, "gzrys");
            return (Criteria) this;
        }

        public Criteria andGzrysNotBetween(String value1, String value2) {
            addCriterion("GZRYS not between", value1, value2, "gzrys");
            return (Criteria) this;
        }

        public Criteria andJssjIsNull() {
            addCriterion("JSSJ is null");
            return (Criteria) this;
        }

        public Criteria andJssjIsNotNull() {
            addCriterion("JSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJssjEqualTo(Date value) {
            addCriterionForJDBCDate("JSSJ =", value, "jssj");
            return (Criteria) this;
        }

        public Criteria andJssjNotEqualTo(Date value) {
            addCriterionForJDBCDate("JSSJ <>", value, "jssj");
            return (Criteria) this;
        }

        public Criteria andJssjGreaterThan(Date value) {
            addCriterionForJDBCDate("JSSJ >", value, "jssj");
            return (Criteria) this;
        }

        public Criteria andJssjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("JSSJ >=", value, "jssj");
            return (Criteria) this;
        }

        public Criteria andJssjLessThan(Date value) {
            addCriterionForJDBCDate("JSSJ <", value, "jssj");
            return (Criteria) this;
        }

        public Criteria andJssjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("JSSJ <=", value, "jssj");
            return (Criteria) this;
        }

        public Criteria andJssjIn(List<Date> values) {
            addCriterionForJDBCDate("JSSJ in", values, "jssj");
            return (Criteria) this;
        }

        public Criteria andJssjNotIn(List<Date> values) {
            addCriterionForJDBCDate("JSSJ not in", values, "jssj");
            return (Criteria) this;
        }

        public Criteria andJssjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("JSSJ between", value1, value2, "jssj");
            return (Criteria) this;
        }

        public Criteria andJssjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("JSSJ not between", value1, value2, "jssj");
            return (Criteria) this;
        }

        public Criteria andGzdwsIsNull() {
            addCriterion("GZDWS is null");
            return (Criteria) this;
        }

        public Criteria andGzdwsIsNotNull() {
            addCriterion("GZDWS is not null");
            return (Criteria) this;
        }

        public Criteria andGzdwsEqualTo(String value) {
            addCriterion("GZDWS =", value, "gzdws");
            return (Criteria) this;
        }

        public Criteria andGzdwsNotEqualTo(String value) {
            addCriterion("GZDWS <>", value, "gzdws");
            return (Criteria) this;
        }

        public Criteria andGzdwsGreaterThan(String value) {
            addCriterion("GZDWS >", value, "gzdws");
            return (Criteria) this;
        }

        public Criteria andGzdwsGreaterThanOrEqualTo(String value) {
            addCriterion("GZDWS >=", value, "gzdws");
            return (Criteria) this;
        }

        public Criteria andGzdwsLessThan(String value) {
            addCriterion("GZDWS <", value, "gzdws");
            return (Criteria) this;
        }

        public Criteria andGzdwsLessThanOrEqualTo(String value) {
            addCriterion("GZDWS <=", value, "gzdws");
            return (Criteria) this;
        }

        public Criteria andGzdwsLike(String value) {
            addCriterion("GZDWS like", value, "gzdws");
            return (Criteria) this;
        }

        public Criteria andGzdwsNotLike(String value) {
            addCriterion("GZDWS not like", value, "gzdws");
            return (Criteria) this;
        }

        public Criteria andGzdwsIn(List<String> values) {
            addCriterion("GZDWS in", values, "gzdws");
            return (Criteria) this;
        }

        public Criteria andGzdwsNotIn(List<String> values) {
            addCriterion("GZDWS not in", values, "gzdws");
            return (Criteria) this;
        }

        public Criteria andGzdwsBetween(String value1, String value2) {
            addCriterion("GZDWS between", value1, value2, "gzdws");
            return (Criteria) this;
        }

        public Criteria andGzdwsNotBetween(String value1, String value2) {
            addCriterion("GZDWS not between", value1, value2, "gzdws");
            return (Criteria) this;
        }

        public Criteria andCjrIsNull() {
            addCriterion("CJR is null");
            return (Criteria) this;
        }

        public Criteria andCjrIsNotNull() {
            addCriterion("CJR is not null");
            return (Criteria) this;
        }

        public Criteria andCjrEqualTo(String value) {
            addCriterion("CJR =", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotEqualTo(String value) {
            addCriterion("CJR <>", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrGreaterThan(String value) {
            addCriterion("CJR >", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrGreaterThanOrEqualTo(String value) {
            addCriterion("CJR >=", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLessThan(String value) {
            addCriterion("CJR <", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLessThanOrEqualTo(String value) {
            addCriterion("CJR <=", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrLike(String value) {
            addCriterion("CJR like", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotLike(String value) {
            addCriterion("CJR not like", value, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrIn(List<String> values) {
            addCriterion("CJR in", values, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotIn(List<String> values) {
            addCriterion("CJR not in", values, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrBetween(String value1, String value2) {
            addCriterion("CJR between", value1, value2, "cjr");
            return (Criteria) this;
        }

        public Criteria andCjrNotBetween(String value1, String value2) {
            addCriterion("CJR not between", value1, value2, "cjr");
            return (Criteria) this;
        }

        public Criteria andXgrIsNull() {
            addCriterion("XGR is null");
            return (Criteria) this;
        }

        public Criteria andXgrIsNotNull() {
            addCriterion("XGR is not null");
            return (Criteria) this;
        }

        public Criteria andXgrEqualTo(String value) {
            addCriterion("XGR =", value, "xgr");
            return (Criteria) this;
        }

        public Criteria andXgrNotEqualTo(String value) {
            addCriterion("XGR <>", value, "xgr");
            return (Criteria) this;
        }

        public Criteria andXgrGreaterThan(String value) {
            addCriterion("XGR >", value, "xgr");
            return (Criteria) this;
        }

        public Criteria andXgrGreaterThanOrEqualTo(String value) {
            addCriterion("XGR >=", value, "xgr");
            return (Criteria) this;
        }

        public Criteria andXgrLessThan(String value) {
            addCriterion("XGR <", value, "xgr");
            return (Criteria) this;
        }

        public Criteria andXgrLessThanOrEqualTo(String value) {
            addCriterion("XGR <=", value, "xgr");
            return (Criteria) this;
        }

        public Criteria andXgrLike(String value) {
            addCriterion("XGR like", value, "xgr");
            return (Criteria) this;
        }

        public Criteria andXgrNotLike(String value) {
            addCriterion("XGR not like", value, "xgr");
            return (Criteria) this;
        }

        public Criteria andXgrIn(List<String> values) {
            addCriterion("XGR in", values, "xgr");
            return (Criteria) this;
        }

        public Criteria andXgrNotIn(List<String> values) {
            addCriterion("XGR not in", values, "xgr");
            return (Criteria) this;
        }

        public Criteria andXgrBetween(String value1, String value2) {
            addCriterion("XGR between", value1, value2, "xgr");
            return (Criteria) this;
        }

        public Criteria andXgrNotBetween(String value1, String value2) {
            addCriterion("XGR not between", value1, value2, "xgr");
            return (Criteria) this;
        }

        public Criteria andSjIsNull() {
            addCriterion("SJ is null");
            return (Criteria) this;
        }

        public Criteria andSjIsNotNull() {
            addCriterion("SJ is not null");
            return (Criteria) this;
        }

        public Criteria andSjEqualTo(Date value) {
            addCriterionForJDBCDate("SJ =", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjNotEqualTo(Date value) {
            addCriterionForJDBCDate("SJ <>", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjGreaterThan(Date value) {
            addCriterionForJDBCDate("SJ >", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SJ >=", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjLessThan(Date value) {
            addCriterionForJDBCDate("SJ <", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SJ <=", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjIn(List<Date> values) {
            addCriterionForJDBCDate("SJ in", values, "sj");
            return (Criteria) this;
        }

        public Criteria andSjNotIn(List<Date> values) {
            addCriterionForJDBCDate("SJ not in", values, "sj");
            return (Criteria) this;
        }

        public Criteria andSjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SJ between", value1, value2, "sj");
            return (Criteria) this;
        }

        public Criteria andSjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SJ not between", value1, value2, "sj");
            return (Criteria) this;
        }

        public Criteria andShipinidIsNull() {
            addCriterion("SHIPINID is null");
            return (Criteria) this;
        }

        public Criteria andShipinidIsNotNull() {
            addCriterion("SHIPINID is not null");
            return (Criteria) this;
        }

        public Criteria andShipinidEqualTo(String value) {
            addCriterion("SHIPINID =", value, "shipinid");
            return (Criteria) this;
        }

        public Criteria andShipinidNotEqualTo(String value) {
            addCriterion("SHIPINID <>", value, "shipinid");
            return (Criteria) this;
        }

        public Criteria andShipinidGreaterThan(String value) {
            addCriterion("SHIPINID >", value, "shipinid");
            return (Criteria) this;
        }

        public Criteria andShipinidGreaterThanOrEqualTo(String value) {
            addCriterion("SHIPINID >=", value, "shipinid");
            return (Criteria) this;
        }

        public Criteria andShipinidLessThan(String value) {
            addCriterion("SHIPINID <", value, "shipinid");
            return (Criteria) this;
        }

        public Criteria andShipinidLessThanOrEqualTo(String value) {
            addCriterion("SHIPINID <=", value, "shipinid");
            return (Criteria) this;
        }

        public Criteria andShipinidLike(String value) {
            addCriterion("SHIPINID like", value, "shipinid");
            return (Criteria) this;
        }

        public Criteria andShipinidNotLike(String value) {
            addCriterion("SHIPINID not like", value, "shipinid");
            return (Criteria) this;
        }

        public Criteria andShipinidIn(List<String> values) {
            addCriterion("SHIPINID in", values, "shipinid");
            return (Criteria) this;
        }

        public Criteria andShipinidNotIn(List<String> values) {
            addCriterion("SHIPINID not in", values, "shipinid");
            return (Criteria) this;
        }

        public Criteria andShipinidBetween(String value1, String value2) {
            addCriterion("SHIPINID between", value1, value2, "shipinid");
            return (Criteria) this;
        }

        public Criteria andShipinidNotBetween(String value1, String value2) {
            addCriterion("SHIPINID not between", value1, value2, "shipinid");
            return (Criteria) this;
        }

        public Criteria andDyjdIsNull() {
            addCriterion("DYJD is null");
            return (Criteria) this;
        }

        public Criteria andDyjdIsNotNull() {
            addCriterion("DYJD is not null");
            return (Criteria) this;
        }

        public Criteria andDyjdEqualTo(String value) {
            addCriterion("DYJD =", value, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDyjdNotEqualTo(String value) {
            addCriterion("DYJD <>", value, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDyjdGreaterThan(String value) {
            addCriterion("DYJD >", value, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDyjdGreaterThanOrEqualTo(String value) {
            addCriterion("DYJD >=", value, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDyjdLessThan(String value) {
            addCriterion("DYJD <", value, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDyjdLessThanOrEqualTo(String value) {
            addCriterion("DYJD <=", value, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDyjdLike(String value) {
            addCriterion("DYJD like", value, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDyjdNotLike(String value) {
            addCriterion("DYJD not like", value, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDyjdIn(List<String> values) {
            addCriterion("DYJD in", values, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDyjdNotIn(List<String> values) {
            addCriterion("DYJD not in", values, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDyjdBetween(String value1, String value2) {
            addCriterion("DYJD between", value1, value2, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDyjdNotBetween(String value1, String value2) {
            addCriterion("DYJD not between", value1, value2, "dyjd");
            return (Criteria) this;
        }

        public Criteria andDywdIsNull() {
            addCriterion("DYWD is null");
            return (Criteria) this;
        }

        public Criteria andDywdIsNotNull() {
            addCriterion("DYWD is not null");
            return (Criteria) this;
        }

        public Criteria andDywdEqualTo(String value) {
            addCriterion("DYWD =", value, "dywd");
            return (Criteria) this;
        }

        public Criteria andDywdNotEqualTo(String value) {
            addCriterion("DYWD <>", value, "dywd");
            return (Criteria) this;
        }

        public Criteria andDywdGreaterThan(String value) {
            addCriterion("DYWD >", value, "dywd");
            return (Criteria) this;
        }

        public Criteria andDywdGreaterThanOrEqualTo(String value) {
            addCriterion("DYWD >=", value, "dywd");
            return (Criteria) this;
        }

        public Criteria andDywdLessThan(String value) {
            addCriterion("DYWD <", value, "dywd");
            return (Criteria) this;
        }

        public Criteria andDywdLessThanOrEqualTo(String value) {
            addCriterion("DYWD <=", value, "dywd");
            return (Criteria) this;
        }

        public Criteria andDywdLike(String value) {
            addCriterion("DYWD like", value, "dywd");
            return (Criteria) this;
        }

        public Criteria andDywdNotLike(String value) {
            addCriterion("DYWD not like", value, "dywd");
            return (Criteria) this;
        }

        public Criteria andDywdIn(List<String> values) {
            addCriterion("DYWD in", values, "dywd");
            return (Criteria) this;
        }

        public Criteria andDywdNotIn(List<String> values) {
            addCriterion("DYWD not in", values, "dywd");
            return (Criteria) this;
        }

        public Criteria andDywdBetween(String value1, String value2) {
            addCriterion("DYWD between", value1, value2, "dywd");
            return (Criteria) this;
        }

        public Criteria andDywdNotBetween(String value1, String value2) {
            addCriterion("DYWD not between", value1, value2, "dywd");
            return (Criteria) this;
        }

        public Criteria andCjbmIsNull() {
            addCriterion("CJBM is null");
            return (Criteria) this;
        }

        public Criteria andCjbmIsNotNull() {
            addCriterion("CJBM is not null");
            return (Criteria) this;
        }

        public Criteria andCjbmEqualTo(String value) {
            addCriterion("CJBM =", value, "cjbm");
            return (Criteria) this;
        }

        public Criteria andCjbmNotEqualTo(String value) {
            addCriterion("CJBM <>", value, "cjbm");
            return (Criteria) this;
        }

        public Criteria andCjbmGreaterThan(String value) {
            addCriterion("CJBM >", value, "cjbm");
            return (Criteria) this;
        }

        public Criteria andCjbmGreaterThanOrEqualTo(String value) {
            addCriterion("CJBM >=", value, "cjbm");
            return (Criteria) this;
        }

        public Criteria andCjbmLessThan(String value) {
            addCriterion("CJBM <", value, "cjbm");
            return (Criteria) this;
        }

        public Criteria andCjbmLessThanOrEqualTo(String value) {
            addCriterion("CJBM <=", value, "cjbm");
            return (Criteria) this;
        }

        public Criteria andCjbmLike(String value) {
            addCriterion("CJBM like", value, "cjbm");
            return (Criteria) this;
        }

        public Criteria andCjbmNotLike(String value) {
            addCriterion("CJBM not like", value, "cjbm");
            return (Criteria) this;
        }

        public Criteria andCjbmIn(List<String> values) {
            addCriterion("CJBM in", values, "cjbm");
            return (Criteria) this;
        }

        public Criteria andCjbmNotIn(List<String> values) {
            addCriterion("CJBM not in", values, "cjbm");
            return (Criteria) this;
        }

        public Criteria andCjbmBetween(String value1, String value2) {
            addCriterion("CJBM between", value1, value2, "cjbm");
            return (Criteria) this;
        }

        public Criteria andCjbmNotBetween(String value1, String value2) {
            addCriterion("CJBM not between", value1, value2, "cjbm");
            return (Criteria) this;
        }

        public Criteria andGzfzrIsNull() {
            addCriterion("GZFZR is null");
            return (Criteria) this;
        }

        public Criteria andGzfzrIsNotNull() {
            addCriterion("GZFZR is not null");
            return (Criteria) this;
        }

        public Criteria andGzfzrEqualTo(String value) {
            addCriterion("GZFZR =", value, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andGzfzrNotEqualTo(String value) {
            addCriterion("GZFZR <>", value, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andGzfzrGreaterThan(String value) {
            addCriterion("GZFZR >", value, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andGzfzrGreaterThanOrEqualTo(String value) {
            addCriterion("GZFZR >=", value, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andGzfzrLessThan(String value) {
            addCriterion("GZFZR <", value, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andGzfzrLessThanOrEqualTo(String value) {
            addCriterion("GZFZR <=", value, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andGzfzrLike(String value) {
            addCriterion("GZFZR like", value, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andGzfzrNotLike(String value) {
            addCriterion("GZFZR not like", value, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andGzfzrIn(List<String> values) {
            addCriterion("GZFZR in", values, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andGzfzrNotIn(List<String> values) {
            addCriterion("GZFZR not in", values, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andGzfzrBetween(String value1, String value2) {
            addCriterion("GZFZR between", value1, value2, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andGzfzrNotBetween(String value1, String value2) {
            addCriterion("GZFZR not between", value1, value2, "gzfzr");
            return (Criteria) this;
        }

        public Criteria andXgsIsNull() {
            addCriterion("XGS is null");
            return (Criteria) this;
        }

        public Criteria andXgsIsNotNull() {
            addCriterion("XGS is not null");
            return (Criteria) this;
        }

        public Criteria andXgsEqualTo(String value) {
            addCriterion("XGS =", value, "xgs");
            return (Criteria) this;
        }

        public Criteria andXgsNotEqualTo(String value) {
            addCriterion("XGS <>", value, "xgs");
            return (Criteria) this;
        }

        public Criteria andXgsGreaterThan(String value) {
            addCriterion("XGS >", value, "xgs");
            return (Criteria) this;
        }

        public Criteria andXgsGreaterThanOrEqualTo(String value) {
            addCriterion("XGS >=", value, "xgs");
            return (Criteria) this;
        }

        public Criteria andXgsLessThan(String value) {
            addCriterion("XGS <", value, "xgs");
            return (Criteria) this;
        }

        public Criteria andXgsLessThanOrEqualTo(String value) {
            addCriterion("XGS <=", value, "xgs");
            return (Criteria) this;
        }

        public Criteria andXgsLike(String value) {
            addCriterion("XGS like", value, "xgs");
            return (Criteria) this;
        }

        public Criteria andXgsNotLike(String value) {
            addCriterion("XGS not like", value, "xgs");
            return (Criteria) this;
        }

        public Criteria andXgsIn(List<String> values) {
            addCriterion("XGS in", values, "xgs");
            return (Criteria) this;
        }

        public Criteria andXgsNotIn(List<String> values) {
            addCriterion("XGS not in", values, "xgs");
            return (Criteria) this;
        }

        public Criteria andXgsBetween(String value1, String value2) {
            addCriterion("XGS between", value1, value2, "xgs");
            return (Criteria) this;
        }

        public Criteria andXgsNotBetween(String value1, String value2) {
            addCriterion("XGS not between", value1, value2, "xgs");
            return (Criteria) this;
        }

        public Criteria andShipinztIsNull() {
            addCriterion("SHIPINZT is null");
            return (Criteria) this;
        }

        public Criteria andShipinztIsNotNull() {
            addCriterion("SHIPINZT is not null");
            return (Criteria) this;
        }

        public Criteria andShipinztEqualTo(String value) {
            addCriterion("SHIPINZT =", value, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andShipinztNotEqualTo(String value) {
            addCriterion("SHIPINZT <>", value, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andShipinztGreaterThan(String value) {
            addCriterion("SHIPINZT >", value, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andShipinztGreaterThanOrEqualTo(String value) {
            addCriterion("SHIPINZT >=", value, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andShipinztLessThan(String value) {
            addCriterion("SHIPINZT <", value, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andShipinztLessThanOrEqualTo(String value) {
            addCriterion("SHIPINZT <=", value, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andShipinztLike(String value) {
            addCriterion("SHIPINZT like", value, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andShipinztNotLike(String value) {
            addCriterion("SHIPINZT not like", value, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andShipinztIn(List<String> values) {
            addCriterion("SHIPINZT in", values, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andShipinztNotIn(List<String> values) {
            addCriterion("SHIPINZT not in", values, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andShipinztBetween(String value1, String value2) {
            addCriterion("SHIPINZT between", value1, value2, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andShipinztNotBetween(String value1, String value2) {
            addCriterion("SHIPINZT not between", value1, value2, "shipinzt");
            return (Criteria) this;
        }

        public Criteria andXcdbldIsNull() {
            addCriterion("XCDBLD is null");
            return (Criteria) this;
        }

        public Criteria andXcdbldIsNotNull() {
            addCriterion("XCDBLD is not null");
            return (Criteria) this;
        }

        public Criteria andXcdbldEqualTo(String value) {
            addCriterion("XCDBLD =", value, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXcdbldNotEqualTo(String value) {
            addCriterion("XCDBLD <>", value, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXcdbldGreaterThan(String value) {
            addCriterion("XCDBLD >", value, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXcdbldGreaterThanOrEqualTo(String value) {
            addCriterion("XCDBLD >=", value, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXcdbldLessThan(String value) {
            addCriterion("XCDBLD <", value, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXcdbldLessThanOrEqualTo(String value) {
            addCriterion("XCDBLD <=", value, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXcdbldLike(String value) {
            addCriterion("XCDBLD like", value, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXcdbldNotLike(String value) {
            addCriterion("XCDBLD not like", value, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXcdbldIn(List<String> values) {
            addCriterion("XCDBLD in", values, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXcdbldNotIn(List<String> values) {
            addCriterion("XCDBLD not in", values, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXcdbldBetween(String value1, String value2) {
            addCriterion("XCDBLD between", value1, value2, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXcdbldNotBetween(String value1, String value2) {
            addCriterion("XCDBLD not between", value1, value2, "xcdbld");
            return (Criteria) this;
        }

        public Criteria andXczbfzrIsNull() {
            addCriterion("XCZBFZR is null");
            return (Criteria) this;
        }

        public Criteria andXczbfzrIsNotNull() {
            addCriterion("XCZBFZR is not null");
            return (Criteria) this;
        }

        public Criteria andXczbfzrEqualTo(String value) {
            addCriterion("XCZBFZR =", value, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andXczbfzrNotEqualTo(String value) {
            addCriterion("XCZBFZR <>", value, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andXczbfzrGreaterThan(String value) {
            addCriterion("XCZBFZR >", value, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andXczbfzrGreaterThanOrEqualTo(String value) {
            addCriterion("XCZBFZR >=", value, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andXczbfzrLessThan(String value) {
            addCriterion("XCZBFZR <", value, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andXczbfzrLessThanOrEqualTo(String value) {
            addCriterion("XCZBFZR <=", value, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andXczbfzrLike(String value) {
            addCriterion("XCZBFZR like", value, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andXczbfzrNotLike(String value) {
            addCriterion("XCZBFZR not like", value, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andXczbfzrIn(List<String> values) {
            addCriterion("XCZBFZR in", values, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andXczbfzrNotIn(List<String> values) {
            addCriterion("XCZBFZR not in", values, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andXczbfzrBetween(String value1, String value2) {
            addCriterion("XCZBFZR between", value1, value2, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andXczbfzrNotBetween(String value1, String value2) {
            addCriterion("XCZBFZR not between", value1, value2, "xczbfzr");
            return (Criteria) this;
        }

        public Criteria andPhIsNull() {
            addCriterion("PH is null");
            return (Criteria) this;
        }

        public Criteria andPhIsNotNull() {
            addCriterion("PH is not null");
            return (Criteria) this;
        }

        public Criteria andPhEqualTo(String value) {
            addCriterion("PH =", value, "ph");
            return (Criteria) this;
        }

        public Criteria andPhNotEqualTo(String value) {
            addCriterion("PH <>", value, "ph");
            return (Criteria) this;
        }

        public Criteria andPhGreaterThan(String value) {
            addCriterion("PH >", value, "ph");
            return (Criteria) this;
        }

        public Criteria andPhGreaterThanOrEqualTo(String value) {
            addCriterion("PH >=", value, "ph");
            return (Criteria) this;
        }

        public Criteria andPhLessThan(String value) {
            addCriterion("PH <", value, "ph");
            return (Criteria) this;
        }

        public Criteria andPhLessThanOrEqualTo(String value) {
            addCriterion("PH <=", value, "ph");
            return (Criteria) this;
        }

        public Criteria andPhLike(String value) {
            addCriterion("PH like", value, "ph");
            return (Criteria) this;
        }

        public Criteria andPhNotLike(String value) {
            addCriterion("PH not like", value, "ph");
            return (Criteria) this;
        }

        public Criteria andPhIn(List<String> values) {
            addCriterion("PH in", values, "ph");
            return (Criteria) this;
        }

        public Criteria andPhNotIn(List<String> values) {
            addCriterion("PH not in", values, "ph");
            return (Criteria) this;
        }

        public Criteria andPhBetween(String value1, String value2) {
            addCriterion("PH between", value1, value2, "ph");
            return (Criteria) this;
        }

        public Criteria andPhNotBetween(String value1, String value2) {
            addCriterion("PH not between", value1, value2, "ph");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwIsNull() {
            addCriterion("ZBFZRZW is null");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwIsNotNull() {
            addCriterion("ZBFZRZW is not null");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwEqualTo(String value) {
            addCriterion("ZBFZRZW =", value, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwNotEqualTo(String value) {
            addCriterion("ZBFZRZW <>", value, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwGreaterThan(String value) {
            addCriterion("ZBFZRZW >", value, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwGreaterThanOrEqualTo(String value) {
            addCriterion("ZBFZRZW >=", value, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwLessThan(String value) {
            addCriterion("ZBFZRZW <", value, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwLessThanOrEqualTo(String value) {
            addCriterion("ZBFZRZW <=", value, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwLike(String value) {
            addCriterion("ZBFZRZW like", value, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwNotLike(String value) {
            addCriterion("ZBFZRZW not like", value, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwIn(List<String> values) {
            addCriterion("ZBFZRZW in", values, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwNotIn(List<String> values) {
            addCriterion("ZBFZRZW not in", values, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwBetween(String value1, String value2) {
            addCriterion("ZBFZRZW between", value1, value2, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andZbfzrzwNotBetween(String value1, String value2) {
            addCriterion("ZBFZRZW not between", value1, value2, "zbfzrzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwIsNull() {
            addCriterion("DBLDZW is null");
            return (Criteria) this;
        }

        public Criteria andDbldzwIsNotNull() {
            addCriterion("DBLDZW is not null");
            return (Criteria) this;
        }

        public Criteria andDbldzwEqualTo(String value) {
            addCriterion("DBLDZW =", value, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwNotEqualTo(String value) {
            addCriterion("DBLDZW <>", value, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwGreaterThan(String value) {
            addCriterion("DBLDZW >", value, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwGreaterThanOrEqualTo(String value) {
            addCriterion("DBLDZW >=", value, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwLessThan(String value) {
            addCriterion("DBLDZW <", value, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwLessThanOrEqualTo(String value) {
            addCriterion("DBLDZW <=", value, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwLike(String value) {
            addCriterion("DBLDZW like", value, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwNotLike(String value) {
            addCriterion("DBLDZW not like", value, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwIn(List<String> values) {
            addCriterion("DBLDZW in", values, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwNotIn(List<String> values) {
            addCriterion("DBLDZW not in", values, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwBetween(String value1, String value2) {
            addCriterion("DBLDZW between", value1, value2, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andDbldzwNotBetween(String value1, String value2) {
            addCriterion("DBLDZW not between", value1, value2, "dbldzw");
            return (Criteria) this;
        }

        public Criteria andTpztIsNull() {
            addCriterion("TPZT is null");
            return (Criteria) this;
        }

        public Criteria andTpztIsNotNull() {
            addCriterion("TPZT is not null");
            return (Criteria) this;
        }

        public Criteria andTpztEqualTo(String value) {
            addCriterion("TPZT =", value, "tpzt");
            return (Criteria) this;
        }

        public Criteria andTpztNotEqualTo(String value) {
            addCriterion("TPZT <>", value, "tpzt");
            return (Criteria) this;
        }

        public Criteria andTpztGreaterThan(String value) {
            addCriterion("TPZT >", value, "tpzt");
            return (Criteria) this;
        }

        public Criteria andTpztGreaterThanOrEqualTo(String value) {
            addCriterion("TPZT >=", value, "tpzt");
            return (Criteria) this;
        }

        public Criteria andTpztLessThan(String value) {
            addCriterion("TPZT <", value, "tpzt");
            return (Criteria) this;
        }

        public Criteria andTpztLessThanOrEqualTo(String value) {
            addCriterion("TPZT <=", value, "tpzt");
            return (Criteria) this;
        }

        public Criteria andTpztLike(String value) {
            addCriterion("TPZT like", value, "tpzt");
            return (Criteria) this;
        }

        public Criteria andTpztNotLike(String value) {
            addCriterion("TPZT not like", value, "tpzt");
            return (Criteria) this;
        }

        public Criteria andTpztIn(List<String> values) {
            addCriterion("TPZT in", values, "tpzt");
            return (Criteria) this;
        }

        public Criteria andTpztNotIn(List<String> values) {
            addCriterion("TPZT not in", values, "tpzt");
            return (Criteria) this;
        }

        public Criteria andTpztBetween(String value1, String value2) {
            addCriterion("TPZT between", value1, value2, "tpzt");
            return (Criteria) this;
        }

        public Criteria andTpztNotBetween(String value1, String value2) {
            addCriterion("TPZT not between", value1, value2, "tpzt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 01 14:06:53 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_TXZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}