package com.lnsoft.bd.fk.po;

import java.util.Date;

public class TXczyTxzy {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.OBJ_ID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String objId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.ZYDL
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String zydl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.GZDDMS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String gzddms;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.GZPQFR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String gzpqfr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.GZNR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String gznr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.ZYRY
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String zyry;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.ZYNR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String zynr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.SSDSMC
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String ssdsmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.GZBZMC
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String gzbzmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.SSDSID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String ssdsid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.GZBZID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String gzbzid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.KGSJ
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private Date kgsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.ZYLX
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String zylx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.SCYA
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String scya;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.GZRYS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String gzrys;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.JSSJ
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private Date jssj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.GZDWS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String gzdws;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.CJR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String cjr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.XGR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String xgr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.SJ
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private Date sj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.SHIPINID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String shipinid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.DYJD
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String dyjd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.DYWD
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String dywd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.CJBM
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String cjbm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.GZFZR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String gzfzr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.XGS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String xgs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.SHIPINZT
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String shipinzt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.XCDBLD
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String xcdbld;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.XCZBFZR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String xczbfzr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.PH
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String ph;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.ZBFZRZW
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String zbfzrzw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.DBLDZW
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String dbldzw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_XCZY_TXZY.TPZT
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	private String tpzt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.OBJ_ID
	 *
	 * @return the value of T_XCZY_TXZY.OBJ_ID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getObjId() {
		return objId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.OBJ_ID
	 *
	 * @param objId
	 *            the value for T_XCZY_TXZY.OBJ_ID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setObjId(String objId) {
		this.objId = objId == null ? null : objId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.ZYDL
	 *
	 * @return the value of T_XCZY_TXZY.ZYDL
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getZydl() {
		return zydl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.ZYDL
	 *
	 * @param zydl
	 *            the value for T_XCZY_TXZY.ZYDL
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setZydl(String zydl) {
		this.zydl = zydl == null ? null : zydl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.GZDDMS
	 *
	 * @return the value of T_XCZY_TXZY.GZDDMS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getGzddms() {
		return gzddms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.GZDDMS
	 *
	 * @param gzddms
	 *            the value for T_XCZY_TXZY.GZDDMS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setGzddms(String gzddms) {
		this.gzddms = gzddms == null ? null : gzddms.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.GZPQFR
	 *
	 * @return the value of T_XCZY_TXZY.GZPQFR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getGzpqfr() {
		return gzpqfr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.GZPQFR
	 *
	 * @param gzpqfr
	 *            the value for T_XCZY_TXZY.GZPQFR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setGzpqfr(String gzpqfr) {
		this.gzpqfr = gzpqfr == null ? null : gzpqfr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.GZNR
	 *
	 * @return the value of T_XCZY_TXZY.GZNR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getGznr() {
		return gznr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.GZNR
	 *
	 * @param gznr
	 *            the value for T_XCZY_TXZY.GZNR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setGznr(String gznr) {
		this.gznr = gznr == null ? null : gznr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.ZYRY
	 *
	 * @return the value of T_XCZY_TXZY.ZYRY
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getZyry() {
		return zyry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.ZYRY
	 *
	 * @param zyry
	 *            the value for T_XCZY_TXZY.ZYRY
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setZyry(String zyry) {
		this.zyry = zyry == null ? null : zyry.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.ZYNR
	 *
	 * @return the value of T_XCZY_TXZY.ZYNR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getZynr() {
		return zynr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.ZYNR
	 *
	 * @param zynr
	 *            the value for T_XCZY_TXZY.ZYNR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setZynr(String zynr) {
		this.zynr = zynr == null ? null : zynr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.SSDSMC
	 *
	 * @return the value of T_XCZY_TXZY.SSDSMC
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getSsdsmc() {
		return ssdsmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.SSDSMC
	 *
	 * @param ssdsmc
	 *            the value for T_XCZY_TXZY.SSDSMC
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setSsdsmc(String ssdsmc) {
		this.ssdsmc = ssdsmc == null ? null : ssdsmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.GZBZMC
	 *
	 * @return the value of T_XCZY_TXZY.GZBZMC
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getGzbzmc() {
		return gzbzmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.GZBZMC
	 *
	 * @param gzbzmc
	 *            the value for T_XCZY_TXZY.GZBZMC
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setGzbzmc(String gzbzmc) {
		this.gzbzmc = gzbzmc == null ? null : gzbzmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.SSDSID
	 *
	 * @return the value of T_XCZY_TXZY.SSDSID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getSsdsid() {
		return ssdsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.SSDSID
	 *
	 * @param ssdsid
	 *            the value for T_XCZY_TXZY.SSDSID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setSsdsid(String ssdsid) {
		this.ssdsid = ssdsid == null ? null : ssdsid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.GZBZID
	 *
	 * @return the value of T_XCZY_TXZY.GZBZID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getGzbzid() {
		return gzbzid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.GZBZID
	 *
	 * @param gzbzid
	 *            the value for T_XCZY_TXZY.GZBZID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setGzbzid(String gzbzid) {
		this.gzbzid = gzbzid == null ? null : gzbzid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.KGSJ
	 *
	 * @return the value of T_XCZY_TXZY.KGSJ
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public Date getKgsj() {
		return kgsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.KGSJ
	 *
	 * @param kgsj
	 *            the value for T_XCZY_TXZY.KGSJ
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setKgsj(Date kgsj) {
		this.kgsj = kgsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.ZYLX
	 *
	 * @return the value of T_XCZY_TXZY.ZYLX
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getZylx() {
		return zylx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.ZYLX
	 *
	 * @param zylx
	 *            the value for T_XCZY_TXZY.ZYLX
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setZylx(String zylx) {
		this.zylx = zylx == null ? null : zylx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.SCYA
	 *
	 * @return the value of T_XCZY_TXZY.SCYA
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getScya() {
		return scya;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.SCYA
	 *
	 * @param scya
	 *            the value for T_XCZY_TXZY.SCYA
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setScya(String scya) {
		this.scya = scya == null ? null : scya.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.GZRYS
	 *
	 * @return the value of T_XCZY_TXZY.GZRYS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getGzrys() {
		return gzrys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.GZRYS
	 *
	 * @param gzrys
	 *            the value for T_XCZY_TXZY.GZRYS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setGzrys(String gzrys) {
		this.gzrys = gzrys == null ? null : gzrys.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.JSSJ
	 *
	 * @return the value of T_XCZY_TXZY.JSSJ
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public Date getJssj() {
		return jssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.JSSJ
	 *
	 * @param jssj
	 *            the value for T_XCZY_TXZY.JSSJ
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setJssj(Date jssj) {
		this.jssj = jssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.GZDWS
	 *
	 * @return the value of T_XCZY_TXZY.GZDWS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getGzdws() {
		return gzdws;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.GZDWS
	 *
	 * @param gzdws
	 *            the value for T_XCZY_TXZY.GZDWS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setGzdws(String gzdws) {
		this.gzdws = gzdws == null ? null : gzdws.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.CJR
	 *
	 * @return the value of T_XCZY_TXZY.CJR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getCjr() {
		return cjr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.CJR
	 *
	 * @param cjr
	 *            the value for T_XCZY_TXZY.CJR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setCjr(String cjr) {
		this.cjr = cjr == null ? null : cjr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.XGR
	 *
	 * @return the value of T_XCZY_TXZY.XGR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getXgr() {
		return xgr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.XGR
	 *
	 * @param xgr
	 *            the value for T_XCZY_TXZY.XGR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setXgr(String xgr) {
		this.xgr = xgr == null ? null : xgr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.SJ
	 *
	 * @return the value of T_XCZY_TXZY.SJ
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public Date getSj() {
		return sj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.SJ
	 *
	 * @param sj
	 *            the value for T_XCZY_TXZY.SJ
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setSj(Date sj) {
		this.sj = sj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.SHIPINID
	 *
	 * @return the value of T_XCZY_TXZY.SHIPINID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getShipinid() {
		return shipinid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.SHIPINID
	 *
	 * @param shipinid
	 *            the value for T_XCZY_TXZY.SHIPINID
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setShipinid(String shipinid) {
		this.shipinid = shipinid == null ? null : shipinid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.DYJD
	 *
	 * @return the value of T_XCZY_TXZY.DYJD
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getDyjd() {
		return dyjd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.DYJD
	 *
	 * @param dyjd
	 *            the value for T_XCZY_TXZY.DYJD
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setDyjd(String dyjd) {
		this.dyjd = dyjd == null ? null : dyjd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.DYWD
	 *
	 * @return the value of T_XCZY_TXZY.DYWD
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getDywd() {
		return dywd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.DYWD
	 *
	 * @param dywd
	 *            the value for T_XCZY_TXZY.DYWD
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setDywd(String dywd) {
		this.dywd = dywd == null ? null : dywd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.CJBM
	 *
	 * @return the value of T_XCZY_TXZY.CJBM
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getCjbm() {
		return cjbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.CJBM
	 *
	 * @param cjbm
	 *            the value for T_XCZY_TXZY.CJBM
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setCjbm(String cjbm) {
		this.cjbm = cjbm == null ? null : cjbm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.GZFZR
	 *
	 * @return the value of T_XCZY_TXZY.GZFZR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getGzfzr() {
		return gzfzr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.GZFZR
	 *
	 * @param gzfzr
	 *            the value for T_XCZY_TXZY.GZFZR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setGzfzr(String gzfzr) {
		this.gzfzr = gzfzr == null ? null : gzfzr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.XGS
	 *
	 * @return the value of T_XCZY_TXZY.XGS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getXgs() {
		return xgs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.XGS
	 *
	 * @param xgs
	 *            the value for T_XCZY_TXZY.XGS
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setXgs(String xgs) {
		this.xgs = xgs == null ? null : xgs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.SHIPINZT
	 *
	 * @return the value of T_XCZY_TXZY.SHIPINZT
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getShipinzt() {
		return shipinzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.SHIPINZT
	 *
	 * @param shipinzt
	 *            the value for T_XCZY_TXZY.SHIPINZT
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setShipinzt(String shipinzt) {
		this.shipinzt = shipinzt == null ? null : shipinzt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.XCDBLD
	 *
	 * @return the value of T_XCZY_TXZY.XCDBLD
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getXcdbld() {
		return xcdbld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.XCDBLD
	 *
	 * @param xcdbld
	 *            the value for T_XCZY_TXZY.XCDBLD
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setXcdbld(String xcdbld) {
		this.xcdbld = xcdbld == null ? null : xcdbld.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.XCZBFZR
	 *
	 * @return the value of T_XCZY_TXZY.XCZBFZR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getXczbfzr() {
		return xczbfzr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.XCZBFZR
	 *
	 * @param xczbfzr
	 *            the value for T_XCZY_TXZY.XCZBFZR
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setXczbfzr(String xczbfzr) {
		this.xczbfzr = xczbfzr == null ? null : xczbfzr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.PH
	 *
	 * @return the value of T_XCZY_TXZY.PH
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getPh() {
		return ph;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.PH
	 *
	 * @param ph
	 *            the value for T_XCZY_TXZY.PH
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setPh(String ph) {
		this.ph = ph == null ? null : ph.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.ZBFZRZW
	 *
	 * @return the value of T_XCZY_TXZY.ZBFZRZW
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getZbfzrzw() {
		return zbfzrzw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.ZBFZRZW
	 *
	 * @param zbfzrzw
	 *            the value for T_XCZY_TXZY.ZBFZRZW
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setZbfzrzw(String zbfzrzw) {
		this.zbfzrzw = zbfzrzw == null ? null : zbfzrzw.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.DBLDZW
	 *
	 * @return the value of T_XCZY_TXZY.DBLDZW
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getDbldzw() {
		return dbldzw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.DBLDZW
	 *
	 * @param dbldzw
	 *            the value for T_XCZY_TXZY.DBLDZW
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setDbldzw(String dbldzw) {
		this.dbldzw = dbldzw == null ? null : dbldzw.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_XCZY_TXZY.TPZT
	 *
	 * @return the value of T_XCZY_TXZY.TPZT
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public String getTpzt() {
		return tpzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_XCZY_TXZY.TPZT
	 *
	 * @param tpzt
	 *            the value for T_XCZY_TXZY.TPZT
	 *
	 * @mbggenerated Thu Nov 01 14:06:53 CST 2018
	 */
	public void setTpzt(String tpzt) {
		this.tpzt = tpzt == null ? null : tpzt.trim();
	}
}