package com.lnsoft.bd.fk.po;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class TXczyZylc implements Serializable {

    private static final long serialVersionUID = -3108268030173156744L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.OBJ_ID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.XH
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private BigDecimal xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.LCMZ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String lcmz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.GZLX
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String gzlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.ZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String zy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.SHZT
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String shzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.PROCINSTID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String procinstid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.ZYXMID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String zyxmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.NODESX
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String nodesx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.SHRMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String shrmc;

    
    private List<TXczyZylcDetails> txczyZylcDetails;
    
    public List<TXczyZylcDetails> getTxczyZylcDetails() {
		return txczyZylcDetails;
	}

	public void setTxczyZylcDetails(List<TXczyZylcDetails> txczyZylcDetails) {
		this.txczyZylcDetails = txczyZylcDetails;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.CJSJ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */

    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.ZYXMMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String zyxmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.SFWC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String sfwc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.WCSJ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mms:ss")
    private Date wcsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.GZLXID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String gzlxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.SFBCMB
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String sfbcmb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.ZYBW
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String zybw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.XKRMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String xkrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC.XKRZH
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String xkrzh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.OBJ_ID
     *
     * @return the value of T_XCZY_ZYLC.OBJ_ID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.OBJ_ID
     *
     * @param objId the value for T_XCZY_ZYLC.OBJ_ID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setObjId(String objId) {
        this.objId = objId == null ? null : objId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.XH
     *
     * @return the value of T_XCZY_ZYLC.XH
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public BigDecimal getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.XH
     *
     * @param xh the value for T_XCZY_ZYLC.XH
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setXh(BigDecimal xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.LCMZ
     *
     * @return the value of T_XCZY_ZYLC.LCMZ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getLcmz() {
        return lcmz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.LCMZ
     *
     * @param lcmz the value for T_XCZY_ZYLC.LCMZ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setLcmz(String lcmz) {
        this.lcmz = lcmz == null ? null : lcmz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.GZLX
     *
     * @return the value of T_XCZY_ZYLC.GZLX
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getGzlx() {
        return gzlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.GZLX
     *
     * @param gzlx the value for T_XCZY_ZYLC.GZLX
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setGzlx(String gzlx) {
        this.gzlx = gzlx == null ? null : gzlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.ZY
     *
     * @return the value of T_XCZY_ZYLC.ZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.ZY
     *
     * @param zy the value for T_XCZY_ZYLC.ZY
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setZy(String zy) {
        this.zy = zy == null ? null : zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.SHZT
     *
     * @return the value of T_XCZY_ZYLC.SHZT
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getShzt() {
        return shzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.SHZT
     *
     * @param shzt the value for T_XCZY_ZYLC.SHZT
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setShzt(String shzt) {
        this.shzt = shzt == null ? null : shzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.PROCINSTID
     *
     * @return the value of T_XCZY_ZYLC.PROCINSTID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getProcinstid() {
        return procinstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.PROCINSTID
     *
     * @param procinstid the value for T_XCZY_ZYLC.PROCINSTID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setProcinstid(String procinstid) {
        this.procinstid = procinstid == null ? null : procinstid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.ZYXMID
     *
     * @return the value of T_XCZY_ZYLC.ZYXMID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getZyxmid() {
        return zyxmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.ZYXMID
     *
     * @param zyxmid the value for T_XCZY_ZYLC.ZYXMID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setZyxmid(String zyxmid) {
        this.zyxmid = zyxmid == null ? null : zyxmid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.NODESX
     *
     * @return the value of T_XCZY_ZYLC.NODESX
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getNodesx() {
        return nodesx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.NODESX
     *
     * @param nodesx the value for T_XCZY_ZYLC.NODESX
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setNodesx(String nodesx) {
        this.nodesx = nodesx == null ? null : nodesx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.SHRMC
     *
     * @return the value of T_XCZY_ZYLC.SHRMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getShrmc() {
        return shrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.SHRMC
     *
     * @param shrmc the value for T_XCZY_ZYLC.SHRMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setShrmc(String shrmc) {
        this.shrmc = shrmc == null ? null : shrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.CJSJ
     *
     * @return the value of T_XCZY_ZYLC.CJSJ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.CJSJ
     *
     * @param cjsj the value for T_XCZY_ZYLC.CJSJ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.ZYXMMC
     *
     * @return the value of T_XCZY_ZYLC.ZYXMMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getZyxmmc() {
        return zyxmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.ZYXMMC
     *
     * @param zyxmmc the value for T_XCZY_ZYLC.ZYXMMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setZyxmmc(String zyxmmc) {
        this.zyxmmc = zyxmmc == null ? null : zyxmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.SFWC
     *
     * @return the value of T_XCZY_ZYLC.SFWC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getSfwc() {
        return sfwc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.SFWC
     *
     * @param sfwc the value for T_XCZY_ZYLC.SFWC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setSfwc(String sfwc) {
        this.sfwc = sfwc == null ? null : sfwc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.WCSJ
     *
     * @return the value of T_XCZY_ZYLC.WCSJ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public Date getWcsj() {
        return wcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.WCSJ
     *
     * @param wcsj the value for T_XCZY_ZYLC.WCSJ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setWcsj(Date wcsj) {
        this.wcsj = wcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.GZLXID
     *
     * @return the value of T_XCZY_ZYLC.GZLXID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getGzlxid() {
        return gzlxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.GZLXID
     *
     * @param gzlxid the value for T_XCZY_ZYLC.GZLXID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setGzlxid(String gzlxid) {
        this.gzlxid = gzlxid == null ? null : gzlxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.SFBCMB
     *
     * @return the value of T_XCZY_ZYLC.SFBCMB
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getSfbcmb() {
        return sfbcmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.SFBCMB
     *
     * @param sfbcmb the value for T_XCZY_ZYLC.SFBCMB
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setSfbcmb(String sfbcmb) {
        this.sfbcmb = sfbcmb == null ? null : sfbcmb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.ZYBW
     *
     * @return the value of T_XCZY_ZYLC.ZYBW
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getZybw() {
        return zybw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.ZYBW
     *
     * @param zybw the value for T_XCZY_ZYLC.ZYBW
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setZybw(String zybw) {
        this.zybw = zybw == null ? null : zybw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.XKRMC
     *
     * @return the value of T_XCZY_ZYLC.XKRMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getXkrmc() {
        return xkrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.XKRMC
     *
     * @param xkrmc the value for T_XCZY_ZYLC.XKRMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setXkrmc(String xkrmc) {
        this.xkrmc = xkrmc == null ? null : xkrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC.XKRZH
     *
     * @return the value of T_XCZY_ZYLC.XKRZH
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getXkrzh() {
        return xkrzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC.XKRZH
     *
     * @param xkrzh the value for T_XCZY_ZYLC.XKRZH
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setXkrzh(String xkrzh) {
        this.xkrzh = xkrzh == null ? null : xkrzh.trim();
    }
}