package com.lnsoft.bd.fk.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TXczyFxdwjExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public TXczyFxdwjExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andObjIdIsNull() {
            addCriterion("OBJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andObjIdIsNotNull() {
            addCriterion("OBJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andObjIdEqualTo(String value) {
            addCriterion("OBJ_ID =", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotEqualTo(String value) {
            addCriterion("OBJ_ID <>", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdGreaterThan(String value) {
            addCriterion("OBJ_ID >", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdGreaterThanOrEqualTo(String value) {
            addCriterion("OBJ_ID >=", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLessThan(String value) {
            addCriterion("OBJ_ID <", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLessThanOrEqualTo(String value) {
            addCriterion("OBJ_ID <=", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLike(String value) {
            addCriterion("OBJ_ID like", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotLike(String value) {
            addCriterion("OBJ_ID not like", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdIn(List<String> values) {
            addCriterion("OBJ_ID in", values, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotIn(List<String> values) {
            addCriterion("OBJ_ID not in", values, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdBetween(String value1, String value2) {
            addCriterion("OBJ_ID between", value1, value2, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotBetween(String value1, String value2) {
            addCriterion("OBJ_ID not between", value1, value2, "objId");
            return (Criteria) this;
        }

        public Criteria andWjmcIsNull() {
            addCriterion("WJMC is null");
            return (Criteria) this;
        }

        public Criteria andWjmcIsNotNull() {
            addCriterion("WJMC is not null");
            return (Criteria) this;
        }

        public Criteria andWjmcEqualTo(String value) {
            addCriterion("WJMC =", value, "wjmc");
            return (Criteria) this;
        }

        public Criteria andWjmcNotEqualTo(String value) {
            addCriterion("WJMC <>", value, "wjmc");
            return (Criteria) this;
        }

        public Criteria andWjmcGreaterThan(String value) {
            addCriterion("WJMC >", value, "wjmc");
            return (Criteria) this;
        }

        public Criteria andWjmcGreaterThanOrEqualTo(String value) {
            addCriterion("WJMC >=", value, "wjmc");
            return (Criteria) this;
        }

        public Criteria andWjmcLessThan(String value) {
            addCriterion("WJMC <", value, "wjmc");
            return (Criteria) this;
        }

        public Criteria andWjmcLessThanOrEqualTo(String value) {
            addCriterion("WJMC <=", value, "wjmc");
            return (Criteria) this;
        }

        public Criteria andWjmcLike(String value) {
            addCriterion("WJMC like", value, "wjmc");
            return (Criteria) this;
        }

        public Criteria andWjmcNotLike(String value) {
            addCriterion("WJMC not like", value, "wjmc");
            return (Criteria) this;
        }

        public Criteria andWjmcIn(List<String> values) {
            addCriterion("WJMC in", values, "wjmc");
            return (Criteria) this;
        }

        public Criteria andWjmcNotIn(List<String> values) {
            addCriterion("WJMC not in", values, "wjmc");
            return (Criteria) this;
        }

        public Criteria andWjmcBetween(String value1, String value2) {
            addCriterion("WJMC between", value1, value2, "wjmc");
            return (Criteria) this;
        }

        public Criteria andWjmcNotBetween(String value1, String value2) {
            addCriterion("WJMC not between", value1, value2, "wjmc");
            return (Criteria) this;
        }

        public Criteria andScsjIsNull() {
            addCriterion("SCSJ is null");
            return (Criteria) this;
        }

        public Criteria andScsjIsNotNull() {
            addCriterion("SCSJ is not null");
            return (Criteria) this;
        }

        public Criteria andScsjEqualTo(Date value) {
            addCriterionForJDBCDate("SCSJ =", value, "scsj");
            return (Criteria) this;
        }

        public Criteria andScsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("SCSJ <>", value, "scsj");
            return (Criteria) this;
        }

        public Criteria andScsjGreaterThan(Date value) {
            addCriterionForJDBCDate("SCSJ >", value, "scsj");
            return (Criteria) this;
        }

        public Criteria andScsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SCSJ >=", value, "scsj");
            return (Criteria) this;
        }

        public Criteria andScsjLessThan(Date value) {
            addCriterionForJDBCDate("SCSJ <", value, "scsj");
            return (Criteria) this;
        }

        public Criteria andScsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SCSJ <=", value, "scsj");
            return (Criteria) this;
        }

        public Criteria andScsjIn(List<Date> values) {
            addCriterionForJDBCDate("SCSJ in", values, "scsj");
            return (Criteria) this;
        }

        public Criteria andScsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("SCSJ not in", values, "scsj");
            return (Criteria) this;
        }

        public Criteria andScsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SCSJ between", value1, value2, "scsj");
            return (Criteria) this;
        }

        public Criteria andScsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SCSJ not between", value1, value2, "scsj");
            return (Criteria) this;
        }

        public Criteria andFxidIsNull() {
            addCriterion("FXID is null");
            return (Criteria) this;
        }

        public Criteria andFxidIsNotNull() {
            addCriterion("FXID is not null");
            return (Criteria) this;
        }

        public Criteria andFxidEqualTo(String value) {
            addCriterion("FXID =", value, "fxid");
            return (Criteria) this;
        }

        public Criteria andFxidNotEqualTo(String value) {
            addCriterion("FXID <>", value, "fxid");
            return (Criteria) this;
        }

        public Criteria andFxidGreaterThan(String value) {
            addCriterion("FXID >", value, "fxid");
            return (Criteria) this;
        }

        public Criteria andFxidGreaterThanOrEqualTo(String value) {
            addCriterion("FXID >=", value, "fxid");
            return (Criteria) this;
        }

        public Criteria andFxidLessThan(String value) {
            addCriterion("FXID <", value, "fxid");
            return (Criteria) this;
        }

        public Criteria andFxidLessThanOrEqualTo(String value) {
            addCriterion("FXID <=", value, "fxid");
            return (Criteria) this;
        }

        public Criteria andFxidLike(String value) {
            addCriterion("FXID like", value, "fxid");
            return (Criteria) this;
        }

        public Criteria andFxidNotLike(String value) {
            addCriterion("FXID not like", value, "fxid");
            return (Criteria) this;
        }

        public Criteria andFxidIn(List<String> values) {
            addCriterion("FXID in", values, "fxid");
            return (Criteria) this;
        }

        public Criteria andFxidNotIn(List<String> values) {
            addCriterion("FXID not in", values, "fxid");
            return (Criteria) this;
        }

        public Criteria andFxidBetween(String value1, String value2) {
            addCriterion("FXID between", value1, value2, "fxid");
            return (Criteria) this;
        }

        public Criteria andFxidNotBetween(String value1, String value2) {
            addCriterion("FXID not between", value1, value2, "fxid");
            return (Criteria) this;
        }

        public Criteria andWjmsIsNull() {
            addCriterion("WJMS is null");
            return (Criteria) this;
        }

        public Criteria andWjmsIsNotNull() {
            addCriterion("WJMS is not null");
            return (Criteria) this;
        }

        public Criteria andWjmsEqualTo(String value) {
            addCriterion("WJMS =", value, "wjms");
            return (Criteria) this;
        }

        public Criteria andWjmsNotEqualTo(String value) {
            addCriterion("WJMS <>", value, "wjms");
            return (Criteria) this;
        }

        public Criteria andWjmsGreaterThan(String value) {
            addCriterion("WJMS >", value, "wjms");
            return (Criteria) this;
        }

        public Criteria andWjmsGreaterThanOrEqualTo(String value) {
            addCriterion("WJMS >=", value, "wjms");
            return (Criteria) this;
        }

        public Criteria andWjmsLessThan(String value) {
            addCriterion("WJMS <", value, "wjms");
            return (Criteria) this;
        }

        public Criteria andWjmsLessThanOrEqualTo(String value) {
            addCriterion("WJMS <=", value, "wjms");
            return (Criteria) this;
        }

        public Criteria andWjmsLike(String value) {
            addCriterion("WJMS like", value, "wjms");
            return (Criteria) this;
        }

        public Criteria andWjmsNotLike(String value) {
            addCriterion("WJMS not like", value, "wjms");
            return (Criteria) this;
        }

        public Criteria andWjmsIn(List<String> values) {
            addCriterion("WJMS in", values, "wjms");
            return (Criteria) this;
        }

        public Criteria andWjmsNotIn(List<String> values) {
            addCriterion("WJMS not in", values, "wjms");
            return (Criteria) this;
        }

        public Criteria andWjmsBetween(String value1, String value2) {
            addCriterion("WJMS between", value1, value2, "wjms");
            return (Criteria) this;
        }

        public Criteria andWjmsNotBetween(String value1, String value2) {
            addCriterion("WJMS not between", value1, value2, "wjms");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 02 16:38:58 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_FXDWJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}