package com.lnsoft.bd.fk.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

public class TXczyZylcDetails implements Serializable {

    private static final long serialVersionUID = 6415481160947780500L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_DETAILS.OBJ_ID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_DETAILS.BZ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private BigDecimal bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_DETAILS.HJMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String hjmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_DETAILS.SFGJFXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String sfgjfxd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_DETAILS.BZLCID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String bzlcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_DETAILS.DDR
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String ddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_DETAILS.DDYJ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String ddyj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_DETAILS.OBJ_ID
     *
     * @return the value of T_XCZY_ZYLC_DETAILS.OBJ_ID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private List<TXczyZylcFxd> txczyZylcFxds;
    
    
    public List<TXczyZylcFxd> getTxczyZylcFxds() {
		return txczyZylcFxds;
	}

	public void setTxczyZylcFxds(List<TXczyZylcFxd> txczyZylcFxds) {
		this.txczyZylcFxds = txczyZylcFxds;
	}

	public String getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_DETAILS.OBJ_ID
     *
     * @param objId the value for T_XCZY_ZYLC_DETAILS.OBJ_ID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setObjId(String objId) {
        this.objId = objId == null ? null : objId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_DETAILS.BZ
     *
     * @return the value of T_XCZY_ZYLC_DETAILS.BZ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public BigDecimal getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_DETAILS.BZ
     *
     * @param bz the value for T_XCZY_ZYLC_DETAILS.BZ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setBz(BigDecimal bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_DETAILS.HJMC
     *
     * @return the value of T_XCZY_ZYLC_DETAILS.HJMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getHjmc() {
        return hjmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_DETAILS.HJMC
     *
     * @param hjmc the value for T_XCZY_ZYLC_DETAILS.HJMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setHjmc(String hjmc) {
        this.hjmc = hjmc == null ? null : hjmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_DETAILS.SFGJFXD
     *
     * @return the value of T_XCZY_ZYLC_DETAILS.SFGJFXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getSfgjfxd() {
        return sfgjfxd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_DETAILS.SFGJFXD
     *
     * @param sfgjfxd the value for T_XCZY_ZYLC_DETAILS.SFGJFXD
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setSfgjfxd(String sfgjfxd) {
        this.sfgjfxd = sfgjfxd == null ? null : sfgjfxd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_DETAILS.BZLCID
     *
     * @return the value of T_XCZY_ZYLC_DETAILS.BZLCID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getBzlcid() {
        return bzlcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_DETAILS.BZLCID
     *
     * @param bzlcid the value for T_XCZY_ZYLC_DETAILS.BZLCID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setBzlcid(String bzlcid) {
        this.bzlcid = bzlcid == null ? null : bzlcid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_DETAILS.DDR
     *
     * @return the value of T_XCZY_ZYLC_DETAILS.DDR
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getDdr() {
        return ddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_DETAILS.DDR
     *
     * @param ddr the value for T_XCZY_ZYLC_DETAILS.DDR
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setDdr(String ddr) {
        this.ddr = ddr == null ? null : ddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_DETAILS.DDYJ
     *
     * @return the value of T_XCZY_ZYLC_DETAILS.DDYJ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getDdyj() {
        return ddyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_DETAILS.DDYJ
     *
     * @param ddyj the value for T_XCZY_ZYLC_DETAILS.DDYJ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setDdyj(String ddyj) {
        this.ddyj = ddyj == null ? null : ddyj.trim();
    }
}