package com.lnsoft.bd.fk.po;

import java.io.Serializable;
import java.math.BigDecimal;

public class TXczyZylcFxd implements Serializable {

    private static final long serialVersionUID = 9180086547249557533L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_FXD.OBJ_ID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_FXD.FXDMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String fxdmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_FXD.FXDNR
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String fxdnr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_FXD.WJM
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String wjm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_FXD.BZID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String bzid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_FXD.FXDBZ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private BigDecimal fxdbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_ZYLC_FXD.ZXR
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    private String zxr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_FXD.OBJ_ID
     *
     * @return the value of T_XCZY_ZYLC_FXD.OBJ_ID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_FXD.OBJ_ID
     *
     * @param objId the value for T_XCZY_ZYLC_FXD.OBJ_ID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setObjId(String objId) {
        this.objId = objId == null ? null : objId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_FXD.FXDMC
     *
     * @return the value of T_XCZY_ZYLC_FXD.FXDMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getFxdmc() {
        return fxdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_FXD.FXDMC
     *
     * @param fxdmc the value for T_XCZY_ZYLC_FXD.FXDMC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setFxdmc(String fxdmc) {
        this.fxdmc = fxdmc == null ? null : fxdmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_FXD.FXDNR
     *
     * @return the value of T_XCZY_ZYLC_FXD.FXDNR
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getFxdnr() {
        return fxdnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_FXD.FXDNR
     *
     * @param fxdnr the value for T_XCZY_ZYLC_FXD.FXDNR
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setFxdnr(String fxdnr) {
        this.fxdnr = fxdnr == null ? null : fxdnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_FXD.WJM
     *
     * @return the value of T_XCZY_ZYLC_FXD.WJM
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getWjm() {
        return wjm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_FXD.WJM
     *
     * @param wjm the value for T_XCZY_ZYLC_FXD.WJM
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setWjm(String wjm) {
        this.wjm = wjm == null ? null : wjm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_FXD.BZID
     *
     * @return the value of T_XCZY_ZYLC_FXD.BZID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getBzid() {
        return bzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_FXD.BZID
     *
     * @param bzid the value for T_XCZY_ZYLC_FXD.BZID
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setBzid(String bzid) {
        this.bzid = bzid == null ? null : bzid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_FXD.FXDBZ
     *
     * @return the value of T_XCZY_ZYLC_FXD.FXDBZ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public BigDecimal getFxdbz() {
        return fxdbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_FXD.FXDBZ
     *
     * @param fxdbz the value for T_XCZY_ZYLC_FXD.FXDBZ
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setFxdbz(BigDecimal fxdbz) {
        this.fxdbz = fxdbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_ZYLC_FXD.ZXR
     *
     * @return the value of T_XCZY_ZYLC_FXD.ZXR
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getZxr() {
        return zxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_ZYLC_FXD.ZXR
     *
     * @param zxr the value for T_XCZY_ZYLC_FXD.ZXR
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setZxr(String zxr) {
        this.zxr = zxr == null ? null : zxr.trim();
    }
}