package com.lnsoft.bd.fk.po;

import java.util.Date;

public class TXczyFxdwj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_FXDWJ.OBJ_ID
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    private String objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_FXDWJ.WJMC
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    private String wjmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_FXDWJ.SCSJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    private Date scsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_FXDWJ.FXID
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    private String fxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XCZY_FXDWJ.WJMS
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    private String wjms;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_FXDWJ.OBJ_ID
     *
     * @return the value of T_XCZY_FXDWJ.OBJ_ID
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public String getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_FXDWJ.OBJ_ID
     *
     * @param objId the value for T_XCZY_FXDWJ.OBJ_ID
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public void setObjId(String objId) {
        this.objId = objId == null ? null : objId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_FXDWJ.WJMC
     *
     * @return the value of T_XCZY_FXDWJ.WJMC
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public String getWjmc() {
        return wjmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_FXDWJ.WJMC
     *
     * @param wjmc the value for T_XCZY_FXDWJ.WJMC
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public void setWjmc(String wjmc) {
        this.wjmc = wjmc == null ? null : wjmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_FXDWJ.SCSJ
     *
     * @return the value of T_XCZY_FXDWJ.SCSJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public Date getScsj() {
        return scsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_FXDWJ.SCSJ
     *
     * @param scsj the value for T_XCZY_FXDWJ.SCSJ
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public void setScsj(Date scsj) {
        this.scsj = scsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_FXDWJ.FXID
     *
     * @return the value of T_XCZY_FXDWJ.FXID
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public String getFxid() {
        return fxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_FXDWJ.FXID
     *
     * @param fxid the value for T_XCZY_FXDWJ.FXID
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public void setFxid(String fxid) {
        this.fxid = fxid == null ? null : fxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XCZY_FXDWJ.WJMS
     *
     * @return the value of T_XCZY_FXDWJ.WJMS
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public String getWjms() {
        return wjms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XCZY_FXDWJ.WJMS
     *
     * @param wjms the value for T_XCZY_FXDWJ.WJMS
     *
     * @mbggenerated Fri Nov 02 16:38:58 CST 2018
     */
    public void setWjms(String wjms) {
        this.wjms = wjms == null ? null : wjms.trim();
    }
}