package com.lnsoft.bd.fk.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TXczyZylcExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public TXczyZylcExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andObjIdIsNull() {
            addCriterion("OBJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andObjIdIsNotNull() {
            addCriterion("OBJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andObjIdEqualTo(String value) {
            addCriterion("OBJ_ID =", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotEqualTo(String value) {
            addCriterion("OBJ_ID <>", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdGreaterThan(String value) {
            addCriterion("OBJ_ID >", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdGreaterThanOrEqualTo(String value) {
            addCriterion("OBJ_ID >=", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLessThan(String value) {
            addCriterion("OBJ_ID <", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLessThanOrEqualTo(String value) {
            addCriterion("OBJ_ID <=", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLike(String value) {
            addCriterion("OBJ_ID like", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotLike(String value) {
            addCriterion("OBJ_ID not like", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdIn(List<String> values) {
            addCriterion("OBJ_ID in", values, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotIn(List<String> values) {
            addCriterion("OBJ_ID not in", values, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdBetween(String value1, String value2) {
            addCriterion("OBJ_ID between", value1, value2, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotBetween(String value1, String value2) {
            addCriterion("OBJ_ID not between", value1, value2, "objId");
            return (Criteria) this;
        }

        public Criteria andXhIsNull() {
            addCriterion("XH is null");
            return (Criteria) this;
        }

        public Criteria andXhIsNotNull() {
            addCriterion("XH is not null");
            return (Criteria) this;
        }

        public Criteria andXhEqualTo(BigDecimal value) {
            addCriterion("XH =", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotEqualTo(BigDecimal value) {
            addCriterion("XH <>", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhGreaterThan(BigDecimal value) {
            addCriterion("XH >", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("XH >=", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhLessThan(BigDecimal value) {
            addCriterion("XH <", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhLessThanOrEqualTo(BigDecimal value) {
            addCriterion("XH <=", value, "xh");
            return (Criteria) this;
        }

        public Criteria andXhIn(List<BigDecimal> values) {
            addCriterion("XH in", values, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotIn(List<BigDecimal> values) {
            addCriterion("XH not in", values, "xh");
            return (Criteria) this;
        }

        public Criteria andXhBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XH between", value1, value2, "xh");
            return (Criteria) this;
        }

        public Criteria andXhNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XH not between", value1, value2, "xh");
            return (Criteria) this;
        }

        public Criteria andLcmzIsNull() {
            addCriterion("LCMZ is null");
            return (Criteria) this;
        }

        public Criteria andLcmzIsNotNull() {
            addCriterion("LCMZ is not null");
            return (Criteria) this;
        }

        public Criteria andLcmzEqualTo(String value) {
            addCriterion("LCMZ =", value, "lcmz");
            return (Criteria) this;
        }

        public Criteria andLcmzNotEqualTo(String value) {
            addCriterion("LCMZ <>", value, "lcmz");
            return (Criteria) this;
        }

        public Criteria andLcmzGreaterThan(String value) {
            addCriterion("LCMZ >", value, "lcmz");
            return (Criteria) this;
        }

        public Criteria andLcmzGreaterThanOrEqualTo(String value) {
            addCriterion("LCMZ >=", value, "lcmz");
            return (Criteria) this;
        }

        public Criteria andLcmzLessThan(String value) {
            addCriterion("LCMZ <", value, "lcmz");
            return (Criteria) this;
        }

        public Criteria andLcmzLessThanOrEqualTo(String value) {
            addCriterion("LCMZ <=", value, "lcmz");
            return (Criteria) this;
        }

        public Criteria andLcmzLike(String value) {
            addCriterion("LCMZ like", value, "lcmz");
            return (Criteria) this;
        }

        public Criteria andLcmzNotLike(String value) {
            addCriterion("LCMZ not like", value, "lcmz");
            return (Criteria) this;
        }

        public Criteria andLcmzIn(List<String> values) {
            addCriterion("LCMZ in", values, "lcmz");
            return (Criteria) this;
        }

        public Criteria andLcmzNotIn(List<String> values) {
            addCriterion("LCMZ not in", values, "lcmz");
            return (Criteria) this;
        }

        public Criteria andLcmzBetween(String value1, String value2) {
            addCriterion("LCMZ between", value1, value2, "lcmz");
            return (Criteria) this;
        }

        public Criteria andLcmzNotBetween(String value1, String value2) {
            addCriterion("LCMZ not between", value1, value2, "lcmz");
            return (Criteria) this;
        }

        public Criteria andGzlxIsNull() {
            addCriterion("GZLX is null");
            return (Criteria) this;
        }

        public Criteria andGzlxIsNotNull() {
            addCriterion("GZLX is not null");
            return (Criteria) this;
        }

        public Criteria andGzlxEqualTo(String value) {
            addCriterion("GZLX =", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxNotEqualTo(String value) {
            addCriterion("GZLX <>", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxGreaterThan(String value) {
            addCriterion("GZLX >", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxGreaterThanOrEqualTo(String value) {
            addCriterion("GZLX >=", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxLessThan(String value) {
            addCriterion("GZLX <", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxLessThanOrEqualTo(String value) {
            addCriterion("GZLX <=", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxLike(String value) {
            addCriterion("GZLX like", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxNotLike(String value) {
            addCriterion("GZLX not like", value, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxIn(List<String> values) {
            addCriterion("GZLX in", values, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxNotIn(List<String> values) {
            addCriterion("GZLX not in", values, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxBetween(String value1, String value2) {
            addCriterion("GZLX between", value1, value2, "gzlx");
            return (Criteria) this;
        }

        public Criteria andGzlxNotBetween(String value1, String value2) {
            addCriterion("GZLX not between", value1, value2, "gzlx");
            return (Criteria) this;
        }

        public Criteria andZyIsNull() {
            addCriterion("ZY is null");
            return (Criteria) this;
        }

        public Criteria andZyIsNotNull() {
            addCriterion("ZY is not null");
            return (Criteria) this;
        }

        public Criteria andZyEqualTo(String value) {
            addCriterion("ZY =", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotEqualTo(String value) {
            addCriterion("ZY <>", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyGreaterThan(String value) {
            addCriterion("ZY >", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyGreaterThanOrEqualTo(String value) {
            addCriterion("ZY >=", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyLessThan(String value) {
            addCriterion("ZY <", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyLessThanOrEqualTo(String value) {
            addCriterion("ZY <=", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyLike(String value) {
            addCriterion("ZY like", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotLike(String value) {
            addCriterion("ZY not like", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyIn(List<String> values) {
            addCriterion("ZY in", values, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotIn(List<String> values) {
            addCriterion("ZY not in", values, "zy");
            return (Criteria) this;
        }

        public Criteria andZyBetween(String value1, String value2) {
            addCriterion("ZY between", value1, value2, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotBetween(String value1, String value2) {
            addCriterion("ZY not between", value1, value2, "zy");
            return (Criteria) this;
        }

        public Criteria andShztIsNull() {
            addCriterion("SHZT is null");
            return (Criteria) this;
        }

        public Criteria andShztIsNotNull() {
            addCriterion("SHZT is not null");
            return (Criteria) this;
        }

        public Criteria andShztEqualTo(String value) {
            addCriterion("SHZT =", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztNotEqualTo(String value) {
            addCriterion("SHZT <>", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztGreaterThan(String value) {
            addCriterion("SHZT >", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztGreaterThanOrEqualTo(String value) {
            addCriterion("SHZT >=", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztLessThan(String value) {
            addCriterion("SHZT <", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztLessThanOrEqualTo(String value) {
            addCriterion("SHZT <=", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztLike(String value) {
            addCriterion("SHZT like", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztNotLike(String value) {
            addCriterion("SHZT not like", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztIn(List<String> values) {
            addCriterion("SHZT in", values, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztNotIn(List<String> values) {
            addCriterion("SHZT not in", values, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztBetween(String value1, String value2) {
            addCriterion("SHZT between", value1, value2, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztNotBetween(String value1, String value2) {
            addCriterion("SHZT not between", value1, value2, "shzt");
            return (Criteria) this;
        }

        public Criteria andProcinstidIsNull() {
            addCriterion("PROCINSTID is null");
            return (Criteria) this;
        }

        public Criteria andProcinstidIsNotNull() {
            addCriterion("PROCINSTID is not null");
            return (Criteria) this;
        }

        public Criteria andProcinstidEqualTo(String value) {
            addCriterion("PROCINSTID =", value, "procinstid");
            return (Criteria) this;
        }

        public Criteria andProcinstidNotEqualTo(String value) {
            addCriterion("PROCINSTID <>", value, "procinstid");
            return (Criteria) this;
        }

        public Criteria andProcinstidGreaterThan(String value) {
            addCriterion("PROCINSTID >", value, "procinstid");
            return (Criteria) this;
        }

        public Criteria andProcinstidGreaterThanOrEqualTo(String value) {
            addCriterion("PROCINSTID >=", value, "procinstid");
            return (Criteria) this;
        }

        public Criteria andProcinstidLessThan(String value) {
            addCriterion("PROCINSTID <", value, "procinstid");
            return (Criteria) this;
        }

        public Criteria andProcinstidLessThanOrEqualTo(String value) {
            addCriterion("PROCINSTID <=", value, "procinstid");
            return (Criteria) this;
        }

        public Criteria andProcinstidLike(String value) {
            addCriterion("PROCINSTID like", value, "procinstid");
            return (Criteria) this;
        }

        public Criteria andProcinstidNotLike(String value) {
            addCriterion("PROCINSTID not like", value, "procinstid");
            return (Criteria) this;
        }

        public Criteria andProcinstidIn(List<String> values) {
            addCriterion("PROCINSTID in", values, "procinstid");
            return (Criteria) this;
        }

        public Criteria andProcinstidNotIn(List<String> values) {
            addCriterion("PROCINSTID not in", values, "procinstid");
            return (Criteria) this;
        }

        public Criteria andProcinstidBetween(String value1, String value2) {
            addCriterion("PROCINSTID between", value1, value2, "procinstid");
            return (Criteria) this;
        }

        public Criteria andProcinstidNotBetween(String value1, String value2) {
            addCriterion("PROCINSTID not between", value1, value2, "procinstid");
            return (Criteria) this;
        }

        public Criteria andZyxmidIsNull() {
            addCriterion("ZYXMID is null");
            return (Criteria) this;
        }

        public Criteria andZyxmidIsNotNull() {
            addCriterion("ZYXMID is not null");
            return (Criteria) this;
        }

        public Criteria andZyxmidEqualTo(String value) {
            addCriterion("ZYXMID =", value, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andZyxmidNotEqualTo(String value) {
            addCriterion("ZYXMID <>", value, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andZyxmidGreaterThan(String value) {
            addCriterion("ZYXMID >", value, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andZyxmidGreaterThanOrEqualTo(String value) {
            addCriterion("ZYXMID >=", value, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andZyxmidLessThan(String value) {
            addCriterion("ZYXMID <", value, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andZyxmidLessThanOrEqualTo(String value) {
            addCriterion("ZYXMID <=", value, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andZyxmidLike(String value) {
            addCriterion("ZYXMID like", value, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andZyxmidNotLike(String value) {
            addCriterion("ZYXMID not like", value, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andZyxmidIn(List<String> values) {
            addCriterion("ZYXMID in", values, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andZyxmidNotIn(List<String> values) {
            addCriterion("ZYXMID not in", values, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andZyxmidBetween(String value1, String value2) {
            addCriterion("ZYXMID between", value1, value2, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andZyxmidNotBetween(String value1, String value2) {
            addCriterion("ZYXMID not between", value1, value2, "zyxmid");
            return (Criteria) this;
        }

        public Criteria andNodesxIsNull() {
            addCriterion("NODESX is null");
            return (Criteria) this;
        }

        public Criteria andNodesxIsNotNull() {
            addCriterion("NODESX is not null");
            return (Criteria) this;
        }

        public Criteria andNodesxEqualTo(String value) {
            addCriterion("NODESX =", value, "nodesx");
            return (Criteria) this;
        }

        public Criteria andNodesxNotEqualTo(String value) {
            addCriterion("NODESX <>", value, "nodesx");
            return (Criteria) this;
        }

        public Criteria andNodesxGreaterThan(String value) {
            addCriterion("NODESX >", value, "nodesx");
            return (Criteria) this;
        }

        public Criteria andNodesxGreaterThanOrEqualTo(String value) {
            addCriterion("NODESX >=", value, "nodesx");
            return (Criteria) this;
        }

        public Criteria andNodesxLessThan(String value) {
            addCriterion("NODESX <", value, "nodesx");
            return (Criteria) this;
        }

        public Criteria andNodesxLessThanOrEqualTo(String value) {
            addCriterion("NODESX <=", value, "nodesx");
            return (Criteria) this;
        }

        public Criteria andNodesxLike(String value) {
            addCriterion("NODESX like", value, "nodesx");
            return (Criteria) this;
        }

        public Criteria andNodesxNotLike(String value) {
            addCriterion("NODESX not like", value, "nodesx");
            return (Criteria) this;
        }

        public Criteria andNodesxIn(List<String> values) {
            addCriterion("NODESX in", values, "nodesx");
            return (Criteria) this;
        }

        public Criteria andNodesxNotIn(List<String> values) {
            addCriterion("NODESX not in", values, "nodesx");
            return (Criteria) this;
        }

        public Criteria andNodesxBetween(String value1, String value2) {
            addCriterion("NODESX between", value1, value2, "nodesx");
            return (Criteria) this;
        }

        public Criteria andNodesxNotBetween(String value1, String value2) {
            addCriterion("NODESX not between", value1, value2, "nodesx");
            return (Criteria) this;
        }

        public Criteria andShrmcIsNull() {
            addCriterion("SHRMC is null");
            return (Criteria) this;
        }

        public Criteria andShrmcIsNotNull() {
            addCriterion("SHRMC is not null");
            return (Criteria) this;
        }

        public Criteria andShrmcEqualTo(String value) {
            addCriterion("SHRMC =", value, "shrmc");
            return (Criteria) this;
        }

        public Criteria andShrmcNotEqualTo(String value) {
            addCriterion("SHRMC <>", value, "shrmc");
            return (Criteria) this;
        }

        public Criteria andShrmcGreaterThan(String value) {
            addCriterion("SHRMC >", value, "shrmc");
            return (Criteria) this;
        }

        public Criteria andShrmcGreaterThanOrEqualTo(String value) {
            addCriterion("SHRMC >=", value, "shrmc");
            return (Criteria) this;
        }

        public Criteria andShrmcLessThan(String value) {
            addCriterion("SHRMC <", value, "shrmc");
            return (Criteria) this;
        }

        public Criteria andShrmcLessThanOrEqualTo(String value) {
            addCriterion("SHRMC <=", value, "shrmc");
            return (Criteria) this;
        }

        public Criteria andShrmcLike(String value) {
            addCriterion("SHRMC like", value, "shrmc");
            return (Criteria) this;
        }

        public Criteria andShrmcNotLike(String value) {
            addCriterion("SHRMC not like", value, "shrmc");
            return (Criteria) this;
        }

        public Criteria andShrmcIn(List<String> values) {
            addCriterion("SHRMC in", values, "shrmc");
            return (Criteria) this;
        }

        public Criteria andShrmcNotIn(List<String> values) {
            addCriterion("SHRMC not in", values, "shrmc");
            return (Criteria) this;
        }

        public Criteria andShrmcBetween(String value1, String value2) {
            addCriterion("SHRMC between", value1, value2, "shrmc");
            return (Criteria) this;
        }

        public Criteria andShrmcNotBetween(String value1, String value2) {
            addCriterion("SHRMC not between", value1, value2, "shrmc");
            return (Criteria) this;
        }

        public Criteria andCjsjIsNull() {
            addCriterion("CJSJ is null");
            return (Criteria) this;
        }

        public Criteria andCjsjIsNotNull() {
            addCriterion("CJSJ is not null");
            return (Criteria) this;
        }

        public Criteria andCjsjEqualTo(Date value) {
            addCriterionForJDBCDate("CJSJ =", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("CJSJ <>", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjGreaterThan(Date value) {
            addCriterionForJDBCDate("CJSJ >", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CJSJ >=", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjLessThan(Date value) {
            addCriterionForJDBCDate("CJSJ <", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CJSJ <=", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjIn(List<Date> values) {
            addCriterionForJDBCDate("CJSJ in", values, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("CJSJ not in", values, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CJSJ between", value1, value2, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CJSJ not between", value1, value2, "cjsj");
            return (Criteria) this;
        }

        public Criteria andZyxmmcIsNull() {
            addCriterion("ZYXMMC is null");
            return (Criteria) this;
        }

        public Criteria andZyxmmcIsNotNull() {
            addCriterion("ZYXMMC is not null");
            return (Criteria) this;
        }

        public Criteria andZyxmmcEqualTo(String value) {
            addCriterion("ZYXMMC =", value, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andZyxmmcNotEqualTo(String value) {
            addCriterion("ZYXMMC <>", value, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andZyxmmcGreaterThan(String value) {
            addCriterion("ZYXMMC >", value, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andZyxmmcGreaterThanOrEqualTo(String value) {
            addCriterion("ZYXMMC >=", value, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andZyxmmcLessThan(String value) {
            addCriterion("ZYXMMC <", value, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andZyxmmcLessThanOrEqualTo(String value) {
            addCriterion("ZYXMMC <=", value, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andZyxmmcLike(String value) {
            addCriterion("ZYXMMC like", value, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andZyxmmcNotLike(String value) {
            addCriterion("ZYXMMC not like", value, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andZyxmmcIn(List<String> values) {
            addCriterion("ZYXMMC in", values, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andZyxmmcNotIn(List<String> values) {
            addCriterion("ZYXMMC not in", values, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andZyxmmcBetween(String value1, String value2) {
            addCriterion("ZYXMMC between", value1, value2, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andZyxmmcNotBetween(String value1, String value2) {
            addCriterion("ZYXMMC not between", value1, value2, "zyxmmc");
            return (Criteria) this;
        }

        public Criteria andSfwcIsNull() {
            addCriterion("SFWC is null");
            return (Criteria) this;
        }

        public Criteria andSfwcIsNotNull() {
            addCriterion("SFWC is not null");
            return (Criteria) this;
        }

        public Criteria andSfwcEqualTo(String value) {
            addCriterion("SFWC =", value, "sfwc");
            return (Criteria) this;
        }

        public Criteria andSfwcNotEqualTo(String value) {
            addCriterion("SFWC <>", value, "sfwc");
            return (Criteria) this;
        }

        public Criteria andSfwcGreaterThan(String value) {
            addCriterion("SFWC >", value, "sfwc");
            return (Criteria) this;
        }

        public Criteria andSfwcGreaterThanOrEqualTo(String value) {
            addCriterion("SFWC >=", value, "sfwc");
            return (Criteria) this;
        }

        public Criteria andSfwcLessThan(String value) {
            addCriterion("SFWC <", value, "sfwc");
            return (Criteria) this;
        }

        public Criteria andSfwcLessThanOrEqualTo(String value) {
            addCriterion("SFWC <=", value, "sfwc");
            return (Criteria) this;
        }

        public Criteria andSfwcLike(String value) {
            addCriterion("SFWC like", value, "sfwc");
            return (Criteria) this;
        }

        public Criteria andSfwcNotLike(String value) {
            addCriterion("SFWC not like", value, "sfwc");
            return (Criteria) this;
        }

        public Criteria andSfwcIn(List<String> values) {
            addCriterion("SFWC in", values, "sfwc");
            return (Criteria) this;
        }

        public Criteria andSfwcNotIn(List<String> values) {
            addCriterion("SFWC not in", values, "sfwc");
            return (Criteria) this;
        }

        public Criteria andSfwcBetween(String value1, String value2) {
            addCriterion("SFWC between", value1, value2, "sfwc");
            return (Criteria) this;
        }

        public Criteria andSfwcNotBetween(String value1, String value2) {
            addCriterion("SFWC not between", value1, value2, "sfwc");
            return (Criteria) this;
        }

        public Criteria andWcsjIsNull() {
            addCriterion("WCSJ is null");
            return (Criteria) this;
        }

        public Criteria andWcsjIsNotNull() {
            addCriterion("WCSJ is not null");
            return (Criteria) this;
        }

        public Criteria andWcsjEqualTo(Date value) {
            addCriterionForJDBCDate("WCSJ =", value, "wcsj");
            return (Criteria) this;
        }

        public Criteria andWcsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("WCSJ <>", value, "wcsj");
            return (Criteria) this;
        }

        public Criteria andWcsjGreaterThan(Date value) {
            addCriterionForJDBCDate("WCSJ >", value, "wcsj");
            return (Criteria) this;
        }

        public Criteria andWcsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("WCSJ >=", value, "wcsj");
            return (Criteria) this;
        }

        public Criteria andWcsjLessThan(Date value) {
            addCriterionForJDBCDate("WCSJ <", value, "wcsj");
            return (Criteria) this;
        }

        public Criteria andWcsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("WCSJ <=", value, "wcsj");
            return (Criteria) this;
        }

        public Criteria andWcsjIn(List<Date> values) {
            addCriterionForJDBCDate("WCSJ in", values, "wcsj");
            return (Criteria) this;
        }

        public Criteria andWcsjNotIn(List<Date> values) {
            addCriterionForJDBCDate("WCSJ not in", values, "wcsj");
            return (Criteria) this;
        }

        public Criteria andWcsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("WCSJ between", value1, value2, "wcsj");
            return (Criteria) this;
        }

        public Criteria andWcsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("WCSJ not between", value1, value2, "wcsj");
            return (Criteria) this;
        }

        public Criteria andGzlxidIsNull() {
            addCriterion("GZLXID is null");
            return (Criteria) this;
        }

        public Criteria andGzlxidIsNotNull() {
            addCriterion("GZLXID is not null");
            return (Criteria) this;
        }

        public Criteria andGzlxidEqualTo(String value) {
            addCriterion("GZLXID =", value, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andGzlxidNotEqualTo(String value) {
            addCriterion("GZLXID <>", value, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andGzlxidGreaterThan(String value) {
            addCriterion("GZLXID >", value, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andGzlxidGreaterThanOrEqualTo(String value) {
            addCriterion("GZLXID >=", value, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andGzlxidLessThan(String value) {
            addCriterion("GZLXID <", value, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andGzlxidLessThanOrEqualTo(String value) {
            addCriterion("GZLXID <=", value, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andGzlxidLike(String value) {
            addCriterion("GZLXID like", value, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andGzlxidNotLike(String value) {
            addCriterion("GZLXID not like", value, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andGzlxidIn(List<String> values) {
            addCriterion("GZLXID in", values, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andGzlxidNotIn(List<String> values) {
            addCriterion("GZLXID not in", values, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andGzlxidBetween(String value1, String value2) {
            addCriterion("GZLXID between", value1, value2, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andGzlxidNotBetween(String value1, String value2) {
            addCriterion("GZLXID not between", value1, value2, "gzlxid");
            return (Criteria) this;
        }

        public Criteria andSfbcmbIsNull() {
            addCriterion("SFBCMB is null");
            return (Criteria) this;
        }

        public Criteria andSfbcmbIsNotNull() {
            addCriterion("SFBCMB is not null");
            return (Criteria) this;
        }

        public Criteria andSfbcmbEqualTo(String value) {
            addCriterion("SFBCMB =", value, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andSfbcmbNotEqualTo(String value) {
            addCriterion("SFBCMB <>", value, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andSfbcmbGreaterThan(String value) {
            addCriterion("SFBCMB >", value, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andSfbcmbGreaterThanOrEqualTo(String value) {
            addCriterion("SFBCMB >=", value, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andSfbcmbLessThan(String value) {
            addCriterion("SFBCMB <", value, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andSfbcmbLessThanOrEqualTo(String value) {
            addCriterion("SFBCMB <=", value, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andSfbcmbLike(String value) {
            addCriterion("SFBCMB like", value, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andSfbcmbNotLike(String value) {
            addCriterion("SFBCMB not like", value, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andSfbcmbIn(List<String> values) {
            addCriterion("SFBCMB in", values, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andSfbcmbNotIn(List<String> values) {
            addCriterion("SFBCMB not in", values, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andSfbcmbBetween(String value1, String value2) {
            addCriterion("SFBCMB between", value1, value2, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andSfbcmbNotBetween(String value1, String value2) {
            addCriterion("SFBCMB not between", value1, value2, "sfbcmb");
            return (Criteria) this;
        }

        public Criteria andZybwIsNull() {
            addCriterion("ZYBW is null");
            return (Criteria) this;
        }

        public Criteria andZybwIsNotNull() {
            addCriterion("ZYBW is not null");
            return (Criteria) this;
        }

        public Criteria andZybwEqualTo(String value) {
            addCriterion("ZYBW =", value, "zybw");
            return (Criteria) this;
        }

        public Criteria andZybwNotEqualTo(String value) {
            addCriterion("ZYBW <>", value, "zybw");
            return (Criteria) this;
        }

        public Criteria andZybwGreaterThan(String value) {
            addCriterion("ZYBW >", value, "zybw");
            return (Criteria) this;
        }

        public Criteria andZybwGreaterThanOrEqualTo(String value) {
            addCriterion("ZYBW >=", value, "zybw");
            return (Criteria) this;
        }

        public Criteria andZybwLessThan(String value) {
            addCriterion("ZYBW <", value, "zybw");
            return (Criteria) this;
        }

        public Criteria andZybwLessThanOrEqualTo(String value) {
            addCriterion("ZYBW <=", value, "zybw");
            return (Criteria) this;
        }

        public Criteria andZybwLike(String value) {
            addCriterion("ZYBW like", value, "zybw");
            return (Criteria) this;
        }

        public Criteria andZybwNotLike(String value) {
            addCriterion("ZYBW not like", value, "zybw");
            return (Criteria) this;
        }

        public Criteria andZybwIn(List<String> values) {
            addCriterion("ZYBW in", values, "zybw");
            return (Criteria) this;
        }

        public Criteria andZybwNotIn(List<String> values) {
            addCriterion("ZYBW not in", values, "zybw");
            return (Criteria) this;
        }

        public Criteria andZybwBetween(String value1, String value2) {
            addCriterion("ZYBW between", value1, value2, "zybw");
            return (Criteria) this;
        }

        public Criteria andZybwNotBetween(String value1, String value2) {
            addCriterion("ZYBW not between", value1, value2, "zybw");
            return (Criteria) this;
        }

        public Criteria andXkrmcIsNull() {
            addCriterion("XKRMC is null");
            return (Criteria) this;
        }

        public Criteria andXkrmcIsNotNull() {
            addCriterion("XKRMC is not null");
            return (Criteria) this;
        }

        public Criteria andXkrmcEqualTo(String value) {
            addCriterion("XKRMC =", value, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrmcNotEqualTo(String value) {
            addCriterion("XKRMC <>", value, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrmcGreaterThan(String value) {
            addCriterion("XKRMC >", value, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrmcGreaterThanOrEqualTo(String value) {
            addCriterion("XKRMC >=", value, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrmcLessThan(String value) {
            addCriterion("XKRMC <", value, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrmcLessThanOrEqualTo(String value) {
            addCriterion("XKRMC <=", value, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrmcLike(String value) {
            addCriterion("XKRMC like", value, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrmcNotLike(String value) {
            addCriterion("XKRMC not like", value, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrmcIn(List<String> values) {
            addCriterion("XKRMC in", values, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrmcNotIn(List<String> values) {
            addCriterion("XKRMC not in", values, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrmcBetween(String value1, String value2) {
            addCriterion("XKRMC between", value1, value2, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrmcNotBetween(String value1, String value2) {
            addCriterion("XKRMC not between", value1, value2, "xkrmc");
            return (Criteria) this;
        }

        public Criteria andXkrzhIsNull() {
            addCriterion("XKRZH is null");
            return (Criteria) this;
        }

        public Criteria andXkrzhIsNotNull() {
            addCriterion("XKRZH is not null");
            return (Criteria) this;
        }

        public Criteria andXkrzhEqualTo(String value) {
            addCriterion("XKRZH =", value, "xkrzh");
            return (Criteria) this;
        }

        public Criteria andXkrzhNotEqualTo(String value) {
            addCriterion("XKRZH <>", value, "xkrzh");
            return (Criteria) this;
        }

        public Criteria andXkrzhGreaterThan(String value) {
            addCriterion("XKRZH >", value, "xkrzh");
            return (Criteria) this;
        }

        public Criteria andXkrzhGreaterThanOrEqualTo(String value) {
            addCriterion("XKRZH >=", value, "xkrzh");
            return (Criteria) this;
        }

        public Criteria andXkrzhLessThan(String value) {
            addCriterion("XKRZH <", value, "xkrzh");
            return (Criteria) this;
        }

        public Criteria andXkrzhLessThanOrEqualTo(String value) {
            addCriterion("XKRZH <=", value, "xkrzh");
            return (Criteria) this;
        }

        public Criteria andXkrzhLike(String value) {
            addCriterion("XKRZH like", value, "xkrzh");
            return (Criteria) this;
        }

        public Criteria andXkrzhNotLike(String value) {
            addCriterion("XKRZH not like", value, "xkrzh");
            return (Criteria) this;
        }

        public Criteria andXkrzhIn(List<String> values) {
            addCriterion("XKRZH in", values, "xkrzh");
            return (Criteria) this;
        }

        public Criteria andXkrzhNotIn(List<String> values) {
            addCriterion("XKRZH not in", values, "xkrzh");
            return (Criteria) this;
        }

        public Criteria andXkrzhBetween(String value1, String value2) {
            addCriterion("XKRZH between", value1, value2, "xkrzh");
            return (Criteria) this;
        }

        public Criteria andXkrzhNotBetween(String value1, String value2) {
            addCriterion("XKRZH not between", value1, value2, "xkrzh");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 01 14:06:53 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_ZYLC
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}