package com.lnsoft.bd.fk.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TXczyZylcDetailsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public TXczyZylcDetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andObjIdIsNull() {
            addCriterion("OBJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andObjIdIsNotNull() {
            addCriterion("OBJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andObjIdEqualTo(String value) {
            addCriterion("OBJ_ID =", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotEqualTo(String value) {
            addCriterion("OBJ_ID <>", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdGreaterThan(String value) {
            addCriterion("OBJ_ID >", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdGreaterThanOrEqualTo(String value) {
            addCriterion("OBJ_ID >=", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLessThan(String value) {
            addCriterion("OBJ_ID <", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLessThanOrEqualTo(String value) {
            addCriterion("OBJ_ID <=", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLike(String value) {
            addCriterion("OBJ_ID like", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotLike(String value) {
            addCriterion("OBJ_ID not like", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdIn(List<String> values) {
            addCriterion("OBJ_ID in", values, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotIn(List<String> values) {
            addCriterion("OBJ_ID not in", values, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdBetween(String value1, String value2) {
            addCriterion("OBJ_ID between", value1, value2, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotBetween(String value1, String value2) {
            addCriterion("OBJ_ID not between", value1, value2, "objId");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(BigDecimal value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(BigDecimal value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(BigDecimal value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(BigDecimal value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<BigDecimal> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<BigDecimal> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andHjmcIsNull() {
            addCriterion("HJMC is null");
            return (Criteria) this;
        }

        public Criteria andHjmcIsNotNull() {
            addCriterion("HJMC is not null");
            return (Criteria) this;
        }

        public Criteria andHjmcEqualTo(String value) {
            addCriterion("HJMC =", value, "hjmc");
            return (Criteria) this;
        }

        public Criteria andHjmcNotEqualTo(String value) {
            addCriterion("HJMC <>", value, "hjmc");
            return (Criteria) this;
        }

        public Criteria andHjmcGreaterThan(String value) {
            addCriterion("HJMC >", value, "hjmc");
            return (Criteria) this;
        }

        public Criteria andHjmcGreaterThanOrEqualTo(String value) {
            addCriterion("HJMC >=", value, "hjmc");
            return (Criteria) this;
        }

        public Criteria andHjmcLessThan(String value) {
            addCriterion("HJMC <", value, "hjmc");
            return (Criteria) this;
        }

        public Criteria andHjmcLessThanOrEqualTo(String value) {
            addCriterion("HJMC <=", value, "hjmc");
            return (Criteria) this;
        }

        public Criteria andHjmcLike(String value) {
            addCriterion("HJMC like", value, "hjmc");
            return (Criteria) this;
        }

        public Criteria andHjmcNotLike(String value) {
            addCriterion("HJMC not like", value, "hjmc");
            return (Criteria) this;
        }

        public Criteria andHjmcIn(List<String> values) {
            addCriterion("HJMC in", values, "hjmc");
            return (Criteria) this;
        }

        public Criteria andHjmcNotIn(List<String> values) {
            addCriterion("HJMC not in", values, "hjmc");
            return (Criteria) this;
        }

        public Criteria andHjmcBetween(String value1, String value2) {
            addCriterion("HJMC between", value1, value2, "hjmc");
            return (Criteria) this;
        }

        public Criteria andHjmcNotBetween(String value1, String value2) {
            addCriterion("HJMC not between", value1, value2, "hjmc");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdIsNull() {
            addCriterion("SFGJFXD is null");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdIsNotNull() {
            addCriterion("SFGJFXD is not null");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdEqualTo(String value) {
            addCriterion("SFGJFXD =", value, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdNotEqualTo(String value) {
            addCriterion("SFGJFXD <>", value, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdGreaterThan(String value) {
            addCriterion("SFGJFXD >", value, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdGreaterThanOrEqualTo(String value) {
            addCriterion("SFGJFXD >=", value, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdLessThan(String value) {
            addCriterion("SFGJFXD <", value, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdLessThanOrEqualTo(String value) {
            addCriterion("SFGJFXD <=", value, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdLike(String value) {
            addCriterion("SFGJFXD like", value, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdNotLike(String value) {
            addCriterion("SFGJFXD not like", value, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdIn(List<String> values) {
            addCriterion("SFGJFXD in", values, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdNotIn(List<String> values) {
            addCriterion("SFGJFXD not in", values, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdBetween(String value1, String value2) {
            addCriterion("SFGJFXD between", value1, value2, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andSfgjfxdNotBetween(String value1, String value2) {
            addCriterion("SFGJFXD not between", value1, value2, "sfgjfxd");
            return (Criteria) this;
        }

        public Criteria andBzlcidIsNull() {
            addCriterion("BZLCID is null");
            return (Criteria) this;
        }

        public Criteria andBzlcidIsNotNull() {
            addCriterion("BZLCID is not null");
            return (Criteria) this;
        }

        public Criteria andBzlcidEqualTo(String value) {
            addCriterion("BZLCID =", value, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andBzlcidNotEqualTo(String value) {
            addCriterion("BZLCID <>", value, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andBzlcidGreaterThan(String value) {
            addCriterion("BZLCID >", value, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andBzlcidGreaterThanOrEqualTo(String value) {
            addCriterion("BZLCID >=", value, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andBzlcidLessThan(String value) {
            addCriterion("BZLCID <", value, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andBzlcidLessThanOrEqualTo(String value) {
            addCriterion("BZLCID <=", value, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andBzlcidLike(String value) {
            addCriterion("BZLCID like", value, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andBzlcidNotLike(String value) {
            addCriterion("BZLCID not like", value, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andBzlcidIn(List<String> values) {
            addCriterion("BZLCID in", values, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andBzlcidNotIn(List<String> values) {
            addCriterion("BZLCID not in", values, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andBzlcidBetween(String value1, String value2) {
            addCriterion("BZLCID between", value1, value2, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andBzlcidNotBetween(String value1, String value2) {
            addCriterion("BZLCID not between", value1, value2, "bzlcid");
            return (Criteria) this;
        }

        public Criteria andDdrIsNull() {
            addCriterion("DDR is null");
            return (Criteria) this;
        }

        public Criteria andDdrIsNotNull() {
            addCriterion("DDR is not null");
            return (Criteria) this;
        }

        public Criteria andDdrEqualTo(String value) {
            addCriterion("DDR =", value, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdrNotEqualTo(String value) {
            addCriterion("DDR <>", value, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdrGreaterThan(String value) {
            addCriterion("DDR >", value, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdrGreaterThanOrEqualTo(String value) {
            addCriterion("DDR >=", value, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdrLessThan(String value) {
            addCriterion("DDR <", value, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdrLessThanOrEqualTo(String value) {
            addCriterion("DDR <=", value, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdrLike(String value) {
            addCriterion("DDR like", value, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdrNotLike(String value) {
            addCriterion("DDR not like", value, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdrIn(List<String> values) {
            addCriterion("DDR in", values, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdrNotIn(List<String> values) {
            addCriterion("DDR not in", values, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdrBetween(String value1, String value2) {
            addCriterion("DDR between", value1, value2, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdrNotBetween(String value1, String value2) {
            addCriterion("DDR not between", value1, value2, "ddr");
            return (Criteria) this;
        }

        public Criteria andDdyjIsNull() {
            addCriterion("DDYJ is null");
            return (Criteria) this;
        }

        public Criteria andDdyjIsNotNull() {
            addCriterion("DDYJ is not null");
            return (Criteria) this;
        }

        public Criteria andDdyjEqualTo(String value) {
            addCriterion("DDYJ =", value, "ddyj");
            return (Criteria) this;
        }

        public Criteria andDdyjNotEqualTo(String value) {
            addCriterion("DDYJ <>", value, "ddyj");
            return (Criteria) this;
        }

        public Criteria andDdyjGreaterThan(String value) {
            addCriterion("DDYJ >", value, "ddyj");
            return (Criteria) this;
        }

        public Criteria andDdyjGreaterThanOrEqualTo(String value) {
            addCriterion("DDYJ >=", value, "ddyj");
            return (Criteria) this;
        }

        public Criteria andDdyjLessThan(String value) {
            addCriterion("DDYJ <", value, "ddyj");
            return (Criteria) this;
        }

        public Criteria andDdyjLessThanOrEqualTo(String value) {
            addCriterion("DDYJ <=", value, "ddyj");
            return (Criteria) this;
        }

        public Criteria andDdyjLike(String value) {
            addCriterion("DDYJ like", value, "ddyj");
            return (Criteria) this;
        }

        public Criteria andDdyjNotLike(String value) {
            addCriterion("DDYJ not like", value, "ddyj");
            return (Criteria) this;
        }

        public Criteria andDdyjIn(List<String> values) {
            addCriterion("DDYJ in", values, "ddyj");
            return (Criteria) this;
        }

        public Criteria andDdyjNotIn(List<String> values) {
            addCriterion("DDYJ not in", values, "ddyj");
            return (Criteria) this;
        }

        public Criteria andDdyjBetween(String value1, String value2) {
            addCriterion("DDYJ between", value1, value2, "ddyj");
            return (Criteria) this;
        }

        public Criteria andDdyjNotBetween(String value1, String value2) {
            addCriterion("DDYJ not between", value1, value2, "ddyj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 01 14:06:53 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XCZY_ZYLC_DETAILS
     *
     * @mbggenerated Thu Nov 01 14:06:53 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}